# Analisi del questionario sul progetto Metroborgo

## Obiettivo dell’analisi

Questo notebook analizza i risultati del questionario dedicato al progetto Metroborgo e alle percezioni relative a Montalto delle Marche.

L’obiettivo è descrivere separatamente:

* i residenti e frequentatori abituali del territorio;
* i visitatori non residenti o non abituali.

L’analisi prende in considerazione il profilo dei rispondenti, le caratteristiche dell’esperienza di visita, le percezioni sul territorio, gli effetti attribuiti al progetto e alcuni aspetti economici.

## Struttura del lavoro

Il procedimento comprende:

1. caricamento e controllo del dataset;
2. separazione dei residenti e dei visitatori;
3. rimozione delle colonne non pertinenti e dei questionari privi di risposte utili;
4. controllo delle compilazioni parziali;
5. analisi descrittiva delle risposte;
6. calcolo di frequenze, percentuali, medie e mediane;
7. raggruppamento delle affermazioni in aree tematiche.

Le percentuali sono calcolate sul numero di risposte valide disponibili per ciascuna domanda. Le risposte mancanti non vengono sostituite con valori stimati.

## Organizzazione del notebook

Il notebook è suddiviso in due sezioni principali:

* analisi dei visitatori;
* analisi dei residenti e frequentatori abituali.

Le interpretazioni conclusive e le visualizzazioni grafiche vengono sviluppate separatamente nella presentazione finale.

## Importazione delle librerie e caricamento dei dati

In questa sezione viene importata la libreria Pandas, utilizzata per leggere, organizzare e analizzare i dati.  
Successivamente viene caricato il file CSV contenente le risposte al questionario.

In [12]:
# Importo la libreria Pandas
import pandas as pd

# Carico il file CSV
df = pd.read_csv("results-survey-07.csv")

# Visualizzo le prime cinque righe del dataset
df.head()

,ID risposta,Data invio,Ultima pagina,Lingua iniziale,Seme,Data di inizio,Data dell'ultima azione,Vivi a Montalto delle Marche o la frequenti abitualmente?,Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?,Quanto sei d’accordo con le seguenti affermazioni? [Sento di poter contribuire attivamente alla vita del mio territorio],...,"Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?","A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?",Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?,Genere,Età:,Titolo di studio,Professione,Professione [Altro],Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?,Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
0,11,2026-02-06 10:35:32,5.0,it,137621747,2026-02-06 10:31:40,2026-02-06 10:35:32,Sì,1–5,7.0,...,Completamente soddisfatto/a,Sì,Oltre 100.000 €,Femmina,46–65,Laurea Magistrale / Laurea Vecchio Ordinamento,Imprenditore / imprenditrice,NaN,Sì,NaN
1,12,2026-02-06 11:47:25,5.0,it,612181227,2026-02-06 11:43:28,2026-02-06 11:47:25,Sì,da sempre,7.0,...,Molto soddisfatto/a,No,NaN,Femmina,31–45,Laurea Magistrale / Laurea Vecchio Ordinamento,Libero/a professionista,NaN,Sì,NaN
2,13,2026-02-06 12:16:49,5.0,it,546677658,2026-02-06 12:13:15,2026-02-06 12:16:49,Sì,da sempre,5.0,...,Abbastanza soddisfatto/a,No,NaN,Femmina,18–30,Laurea Triennale,Studente/studentessa,NaN,Sì,NaN
3,14,2026-02-06 12:34:25,5.0,it,1748246674,2026-02-06 12:13:46,2026-02-06 12:34:25,Sì,da sempre,5.0,...,Abbastanza soddisfatto/a,No,NaN,Femmina,18–30,Laurea Triennale,Studente/studentessa,NaN,No,Spero che tutto ciò porti veramente a qualche ...
4,15,2026-02-06 12:24:03,5.0,it,1858134390,2026-02-06 12:15:25,2026-02-06 12:24:03,Sì,da sempre,7.0,...,Abbastanza soddisfatto/a,No,NaN,Femmina,46–65,Laurea Magistrale / Laurea Vecchio Ordinamento,Libero/a professionista,NaN,Sì,NaN

## Controllo iniziale del dataset

Verifico che il file sia stato caricato correttamente e controllo il numero totale di questionari.

In [21]:
# Controllo il numero totale di risposte presenti nel dataset
numero_risposte = df.shape[0]

print("Numero totale di risposte:", numero_risposte)

# Visualizzo le prime cinque righe per verificare il corretto caricamento
df.head()

Numero totale di risposte: 208

,ID risposta,Data invio,Ultima pagina,Lingua iniziale,Seme,Data di inizio,Data dell'ultima azione,Vivi a Montalto delle Marche o la frequenti abitualmente?,Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?,Quanto sei d’accordo con le seguenti affermazioni? [Sento di poter contribuire attivamente alla vita del mio territorio],...,"Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?","A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?",Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?,Genere,Età:,Titolo di studio,Professione,Professione [Altro],Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?,Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
0,11,2026-02-06 10:35:32,5.0,it,137621747,2026-02-06 10:31:40,2026-02-06 10:35:32,Sì,1–5,7.0,...,Completamente soddisfatto/a,Sì,Oltre 100.000 €,Femmina,46–65,Laurea Magistrale / Laurea Vecchio Ordinamento,Imprenditore / imprenditrice,NaN,Sì,NaN
1,12,2026-02-06 11:47:25,5.0,it,612181227,2026-02-06 11:43:28,2026-02-06 11:47:25,Sì,da sempre,7.0,...,Molto soddisfatto/a,No,NaN,Femmina,31–45,Laurea Magistrale / Laurea Vecchio Ordinamento,Libero/a professionista,NaN,Sì,NaN
2,13,2026-02-06 12:16:49,5.0,it,546677658,2026-02-06 12:13:15,2026-02-06 12:16:49,Sì,da sempre,5.0,...,Abbastanza soddisfatto/a,No,NaN,Femmina,18–30,Laurea Triennale,Studente/studentessa,NaN,Sì,NaN
3,14,2026-02-06 12:34:25,5.0,it,1748246674,2026-02-06 12:13:46,2026-02-06 12:34:25,Sì,da sempre,5.0,...,Abbastanza soddisfatto/a,No,NaN,Femmina,18–30,Laurea Triennale,Studente/studentessa,NaN,No,Spero che tutto ciò porti veramente a qualche ...
4,15,2026-02-06 12:24:03,5.0,it,1858134390,2026-02-06 12:15:25,2026-02-06 12:24:03,Sì,da sempre,7.0,...,Abbastanza soddisfatto/a,No,NaN,Femmina,46–65,Laurea Magistrale / Laurea Vecchio Ordinamento,Libero/a professionista,NaN,Sì,NaN

## Suddivisione del campione

Il questionario distingue gli intervistati in base alla domanda:

**“Vivi a Montalto delle Marche o la frequenti abitualmente?”**

Le risposte vengono utilizzate per creare due gruppi:

- **Residenti o frequentatori abituali**: risposte “Sì”
- **Non residenti o frequentatori non abituali**: risposte “No”

La suddivisione mantiene tutte le risposte associate a ciascun partecipante, poiché ogni riga del dataset rappresenta un questionario completo.

In [22]:
# Nome della colonna utilizzata per suddividere il campione
colonna_residenza = (
    "Vivi a Montalto delle Marche o la frequenti abitualmente?"
)

# Controllo delle risposte presenti nella colonna
df[colonna_residenza].value_counts(dropna=False)

Vivi a Montalto delle Marche o la frequenti abitualmente?
Sì     123
No      83
NaN      2
Name: count, dtype: int64

## Rimozione delle risposte mancanti e creazione dei gruppi

I due questionari privi di risposta alla domanda di suddivisione vengono esclusi dall’analisi comparativa.

Il campione valido viene quindi diviso in due DataFrame:

* residenti o frequentatori abituali;
* non residenti o frequentatori non abituali.

In [23]:
# Nome della colonna utilizzata per suddividere il campione
colonna_residenza = (
    "Vivi a Montalto delle Marche o la frequenti abitualmente?"
)

# Creo una copia del dataset eliminando solamente le righe
# prive di risposta alla domanda di suddivisione
df_valido = df.dropna(subset=[colonna_residenza]).copy()

# Creo il DataFrame dei residenti o frequentatori abituali
df_residenti = df_valido[
    df_valido[colonna_residenza] == "Sì"
].copy()

# Creo il DataFrame dei non residenti o frequentatori non abituali
df_turisti = df_valido[
    df_valido[colonna_residenza] == "No"
].copy()

# Reimposto gli indici dei due DataFrame
df_residenti.reset_index(drop=True, inplace=True)
df_turisti.reset_index(drop=True, inplace=True)

# Verifico il numero di risposte nei due gruppi
print("Risposte valide totali:", len(df_valido))
print("Residenti o frequentatori abituali:", len(df_residenti))
print("Non residenti o frequentatori non abituali:", len(df_turisti))

Risposte valide totali: 206
Residenti o frequentatori abituali: 123
Non residenti o frequentatori non abituali: 83

## Controllo e pulizia iniziale del DataFrame dei turisti

Prima di analizzare le risposte, viene controllata la struttura del DataFrame dedicato ai turisti.

In particolare:

1. vengono visualizzate tutte le colonne;
2. viene contato il numero di risposte presenti in ciascuna colonna;
3. vengono individuate ed eliminate le colonne completamente vuote;
4. vengono cercate eventuali righe prive di risposte utili.

Il DataFrame originale `df_turisti` viene conservato, mentre le operazioni di pulizia vengono applicate a una copia.

In [24]:
# Stampo tutti gli header presenti nel DataFrame dei turisti
for numero, colonna in enumerate(df_turisti.columns, start=1):
    print(f"{numero}. {colonna}")

print("\nNumero totale di colonne:", len(df_turisti.columns))

1. ID risposta
2. Data invio
3. Ultima pagina
4. Lingua iniziale
5. Seme
6. Data di inizio
7. Data dell'ultima azione
8. Vivi a Montalto delle Marche o la frequenti abitualmente?
9. Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?
10. Quanto sei d’accordo con le seguenti affermazioni? [Sento di poter contribuire attivamente alla vita del mio territorio]
11. Quanto sei d’accordo con le seguenti affermazioni? [Quando vedo un problema o un’opportunità nel paese, penso di poter fare qualcosa]
12. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento ascoltato/a quando esprimo idee o proposte sul futuro del territorio]
13. Quanto sei d’accordo con le seguenti affermazioni? [Ho fiducia nella mia capacità di avviare o partecipare a iniziative locali]
14. Quanto sei d’accordo con le seguenti affermazioni? [Nel mio territorio le persone collaborano tra loro]
15. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento parte di una comunità]
16. Quanto sei d’accordo con le seguenti affermazioni? [C’è fiducia reciproca tra abitanti, associazioni e operatori locali]
17. Grazie alle attività del progetto Metroborgo, hai percepito un miglioramento della tua vita sociale?
18. Grazie al progetto Metroborgo hai dialogato con chi ha un background culturale differente dal tuo?
19. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento emotivamente legato/a a questo luogo]
20. Quanto sei d’accordo con le seguenti affermazioni? [Sono orgoglioso/a di vivere qui]
21. Quanto sei d’accordo con le seguenti affermazioni? [Questo territorio rappresenta una parte importante di chi sono]
22. Quanto sei d’accordo con le seguenti affermazioni? [Mi dispiacerebbe molto dover lasciare questo luogo]
23. Quanto sei d’accordo con le seguenti affermazioni? [Partecipo ad attività culturali locali (eventi, laboratori, incontri)]
24. Quanto sei d’accordo con le seguenti affermazioni? [Gli spazi culturali mi stimolano a imparare cose nuove]
25. Quanto sei d’accordo con le seguenti affermazioni? [Le attività culturali mi fanno riflettere sul presente e sul futuro del territorio]
26. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento coinvolto/a, non solo spettatore/trice]
27. Quanto sei d’accordo con le seguenti affermazioni? [La cultura ha un ruolo importante nella mia vita quotidiana]
28. Quanto sei d’accordo con le seguenti affermazioni? [Presto attenzione alla cura degli spazi pubblici]
29. Quanto sei d’accordo con le seguenti affermazioni? [Penso alle conseguenze future delle scelte fatte oggi sul territorio]
30. Quanto sei d’accordo con le seguenti affermazioni? [Nella mia vita quotidiana presto attenzione a ridurre l’impatto ambientale delle mie azioni nel territorio in cui vivo]
31. Quanto sei d’accordo con le seguenti affermazioni? [Cerco di adottare comportamenti rispettosi dell’ambiente negli spazi pubblici e culturali (rifiuti, energia, mobilità, uso delle risorse)]
32. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento soddisfatto/a della mia vita nel territorio]
33. Quanto sei d’accordo con le seguenti affermazioni? [Vivo questo luogo come un ambiente che favorisce il benessere]
34. Quanto sei d’accordo con le seguenti affermazioni? [Le relazioni sociali contribuiscono positivamente alla mia qualità della vita]
35. Quanto sei d’accordo con le seguenti affermazioni? [Vedo prospettive positive per il futuro della comunità]
36. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento mentalmente ed emotivamente a mio agio qui]
37. Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?
38. Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
39. È la tua prima visita a Montalto delle Marche?
40. Che tipo di visita hai o stai realizzando?
41. Qual'è il motivo principale della tua visita?
42. Con chi hai visitato Montalto delle Marche?
43. Hai partecipato ad eventi?
44. A quale evento hai partecipato?
45. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza complessiva è stata di alta qualità]
46. Quanto sei d’accordo con le seguenti affermazioni? [L'esperienza di visita mi ha fatto sentire accolto/a]
47. Quanto sei d’accordo con le seguenti affermazioni? [Gli spazi sono stati chiari e accessibili]
48. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza è stata autentica]
49. Quanto sei d’accordo con le seguenti affermazioni? [Le attività mi hanno aiutato a comprendere il territorio]
50. Quanto sei d’accordo con le seguenti affermazioni? [Ho imparato qualcosa di nuovo]
51. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza culturale mi ha coinvolto/a, non solo come spettatore/trice]
52. Quanto sei d’accordo con le seguenti affermazioni? [Le storie e i luoghi mi hanno colpito emotivamente]
53. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto riflettere]
54. Quanto sei d’accordo con le seguenti affermazioni? [Ho rispettato i luoghi e le persone]
55. Quanto sei d’accordo con le seguenti affermazioni? [Sono stato/a attento/a all’impatto delle mie azioni]
56. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha reso più consapevole del valore del territorio]
57. Quanto sei d’accordo con le seguenti affermazioni? [Mi sentirei responsabile nel tornare come visitatore]
58. Quanto sei d’accordo con le seguenti affermazioni? [Ho interagito con persone del luogo]
59. Quanto sei d’accordo con le seguenti affermazioni? [Ho utilizzato servizi o prodotti locali]
60. Quanto sei d’accordo con le seguenti affermazioni? [Sento di aver contribuito positivamente al territorio]
61. Quanto sei d’accordo con le seguenti affermazioni? [Consiglierei questa esperienza ad altri]
62. Quanto sei d’accordo con le seguenti affermazioni? [Tornerei o rimarrei più a lungo]
63. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto stare bene]
64. Quanto sei d’accordo con le seguenti affermazioni? [Mi sono sentito/a rilassato/a e stimolato/a]
65. Quanto sei d’accordo con le seguenti affermazioni? [Ho vissuto un senso di connessione con il luogo]
66. Quanto sei d’accordo con le seguenti affermazioni? [Questa esperienza ha arricchito il mio tempo]
67. Quanto sei d’accordo con le seguenti affermazioni? [Me ne vado con una sensazione positiva]
68. Durante la tua permanenza, quanto hai speso complessivamente o prevedi di spendere (includendo alloggio, ristorazione, acquisti, trasporti e attività)?
69. Cosa ti ha colpito di più di questa esperienza e perché?
70. A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?
71. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]
72. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]
73. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]
74. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]
75. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]
76. Come valuti il cambiamento della qualità dell’ambiente (paesaggio urbano, spazi pubblici, servizi pubblici) dopo gli investimenti realizzati con il progetto Metroborgo?
77. Nel complesso, in che misura gli investimenti realizzati dal progetto Metroborgo hanno influenzato la qualità della tua vita?
78. Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?
79. A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?
80. Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?
81. Genere
82. Età:
83. Titolo di studio
84. Professione
85. Professione [Altro]
86. Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?
87. Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?

Numero totale di colonne: 87

### Numero di risposte presenti per colonna

Per ogni domanda viene contato il numero di valori non mancanti. Questo controllo permette di distinguere le colonne utilizzate da quelle completamente vuote.

In [25]:
# Conto il numero di valori non mancanti per ogni colonna
conteggio_risposte_turisti = df_turisti.notna().sum()

# Trasformo il risultato in una tabella più leggibile
riepilogo_colonne_turisti = (
    conteggio_risposte_turisti
    .reset_index()
)

riepilogo_colonne_turisti.columns = [
    "Colonna",
    "Numero di risposte"
]

# Aggiungo il numero di valori mancanti
riepilogo_colonne_turisti["Valori mancanti"] = (
    len(df_turisti)
    - riepilogo_colonne_turisti["Numero di risposte"]
)

riepilogo_colonne_turisti

,Colonna,Numero di risposte,Valori mancanti
0,ID risposta,83,0
1,Data invio,68,15
2,Ultima pagina,83,0
3,Lingua iniziale,83,0
4,Seme,83,0
5,Data di inizio,83,0
6,Data dell'ultima azione,83,0
7,Vivi a Montalto delle Marche o la frequenti ab...,83,0
8,Da quanti anni vivi a/frequenti abitualmente M...,0,83
9,Quanto sei d’accordo con le seguenti affermazi...,0,83
10,Quanto sei d’accordo con le seguenti affermazi...,0,83
11,Quanto sei d’accordo con le seguenti affermazi...,0,83
12,Quanto sei d’accordo con le seguenti affermazi...,0,83
13,Quanto sei d’accordo con le seguenti affermazi...,0,83
14,Quanto sei d’accordo con le seguenti affermazi...,0,83
15,Quanto sei d’accordo con le seguenti affermazi...,0,83
16,"Grazie alle attività del progetto Metroborgo, ...",0,83
17,Grazie al progetto Metroborgo hai dialogato co...,0,83
18,Quanto sei d’accordo con le seguenti affermazi...,0,83
19,Quanto sei d’accordo con le seguenti affermazi...,0,83
20,Quanto sei d’accordo con le seguenti affermazi...,0,83
21,Quanto sei d’accordo con le seguenti affermazi...,0,83
22,Quanto sei d’accordo con le seguenti affermazi...,0,83
23,Quanto sei d’accordo con le seguenti affermazi...,0,83
24,Quanto sei d’accordo con le seguenti affermazi...,0,83
25,Quanto sei d’accordo con le seguenti affermazi...,0,83
26,Quanto sei d’accordo con le seguenti affermazi...,0,83
27,Quanto sei d’accordo con le seguenti affermazi...,0,83
28,Quanto sei d’accordo con le seguenti affermazi...,0,83
29,Quanto sei d’accordo con le seguenti affermazi...,0,83
30,Quanto sei d’accordo con le seguenti affermazi...,0,83
31,Quanto sei d’accordo con le seguenti affermazi...,0,83
32,Quanto sei d’accordo con le seguenti affermazi...,0,83
33,Quanto sei d’accordo con le seguenti affermazi...,0,83
34,Quanto sei d’accordo con le seguenti affermazi...,0,83
35,Quanto sei d’accordo con le seguenti affermazi...,0,83
36,Credi che il progetto Metroborgo possa favorir...,0,83
37,"Cosa ti aspetti che cambi, grazie al progetto ...",0,83
38,È la tua prima visita a Montalto delle Marche?,72,11
39,Che tipo di visita hai o stai realizzando?,72,11
40,Qual'è il motivo principale della tua visita?,72,11
41,Con chi hai visitato Montalto delle Marche?,72,11
42,Hai partecipato ad eventi?,72,11
43,A quale evento hai partecipato?,29,54
44,Quanto sei d’accordo con le seguenti affermazi...,70,13
45,Quanto sei d’accordo con le seguenti affermazi...,70,13
46,Quanto sei d’accordo con le seguenti affermazi...,70,13
47,Quanto sei d’accordo con le seguenti affermazi...,70,13
48,Quanto sei d’accordo con le seguenti affermazi...,70,13
49,Quanto sei d’accordo con le seguenti affermazi...,70,13
50,Quanto sei d’accordo con le seguenti affermazi...,70,13
51,Quanto sei d’accordo con le seguenti affermazi...,70,13
52,Quanto sei d’accordo con le seguenti affermazi...,70,13
53,Quanto sei d’accordo con le seguenti affermazi...,70,13
54,Quanto sei d’accordo con le seguenti affermazi...,70,13
55,Quanto sei d’accordo con le seguenti affermazi...,70,13
56,Quanto sei d’accordo con le seguenti affermazi...,70,13
57,Quanto sei d’accordo con le seguenti affermazi...,70,13
58,Quanto sei d’accordo con le seguenti affermazi...,70,13
59,Quanto sei d’accordo con le seguenti affermazi...,70,13
60,Quanto sei d’accordo con le seguenti affermazi...,70,13
61,Quanto sei d’accordo con le seguenti affermazi...,69,14
62,Quanto sei d’accordo con le seguenti affermazi...,70,13
63,Quanto sei d’accordo con le seguenti affermazi...,70,13
64,Quanto sei d’accordo con le seguenti affermazi...,70,13
65,Quanto sei d’accordo con le seguenti affermazi...,70,13
66,Quanto sei d’accordo con le seguenti affermazi...,70,13
67,"Durante la tua permanenza, quanto hai speso co...",70,13
68,Cosa ti ha colpito di più di questa esperienza...,10,73
69,A seguito degli investimenti realizzati con il...,0,83
70,A seguito degli investimenti realizzati con il...,83,0
71,A seguito degli investimenti realizzati con il...,83,0
72,A seguito degli investimenti realizzati con il...,83,0
73,A seguito degli investimenti realizzati con il...,83,0
74,A seguito degli investimenti realizzati con il...,83,0
75,Come valuti il cambiamento della qualità dell’...,0,83
76,"Nel complesso, in che misura gli investimenti ...",0,83
77,"Nel complesso, quanto sei soddisfatto/a degli ...",0,83
78,"A seguito del progetto Metroborgo, hai effettu...",0,83
79,Qual è stato approssimativamente l’ammontare c...,0,83
80,Genere,68,15
81,Età:,68,15
82,Titolo di studio,68,15
83,Professione,68,15
84,Professione [Altro],1,82
85,Credi che il progetto Metroborgo abbia contrib...,68,15
86,Pensieri liberi. C’è qualcos’altro che vorrest...,3,80

### Rimozione delle colonne non pertinenti al gruppo dei turisti

Nel DataFrame dei turisti sono presenti alcune domande rivolte esclusivamente ai residenti. Poiché queste colonne non contengono alcuna risposta nel gruppo analizzato, vengono rimosse.

In questa fase non vengono eliminate righe, perché alcuni questionari potrebbero essere stati compilati solo parzialmente.

In [27]:
# Individuo le colonne completamente vuote nel gruppo dei turisti
colonne_vuote_turisti = df_turisti.columns[
    df_turisti.isna().all()
].tolist()

# Creo una copia eliminando solamente le colonne completamente vuote
df_turisti_pulito = df_turisti.drop(
    columns=colonne_vuote_turisti
).copy()

print("Colonne originali:", df_turisti.shape[1])
print("Colonne completamente vuote eliminate:", len(colonne_vuote_turisti))
print("Colonne rimaste:", df_turisti_pulito.shape[1])

Colonne originali: 87
Colonne completamente vuote eliminate: 36
Colonne rimaste: 51

### Controllo delle colonne rimaste

Dopo aver eliminato le colonne completamente vuote, vengono esaminate le 51 colonne rimaste, visualizzandone il nome completo e il numero di risposte presenti.

Questo controllo permette di distinguere le informazioni tecniche, le domande rivolte ai turisti, i dati sociodemografici e le eventuali colonne anomale.

In [28]:
# Mostro interamente il testo contenuto nelle colonne della tabella
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

# Creo il riepilogo delle colonne rimaste
riepilogo_turisti_pulito = pd.DataFrame({
    "Colonna": df_turisti_pulito.columns,
    "Numero di risposte": df_turisti_pulito.notna().sum().values,
    "Valori mancanti": df_turisti_pulito.isna().sum().values
})

riepilogo_turisti_pulito

,Colonna,Numero di risposte,Valori mancanti
0,ID risposta,83,0
1,Data invio,68,15
2,Ultima pagina,83,0
3,Lingua iniziale,83,0
4,Seme,83,0
5,Data di inizio,83,0
6,Data dell'ultima azione,83,0
7,Vivi a Montalto delle Marche o la frequenti abitualmente?,83,0
8,È la tua prima visita a Montalto delle Marche?,72,11
9,Che tipo di visita hai o stai realizzando?,72,11
10,Qual'è il motivo principale della tua visita?,72,11
11,Con chi hai visitato Montalto delle Marche?,72,11
12,Hai partecipato ad eventi?,72,11
13,A quale evento hai partecipato?,29,54
14,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza complessiva è stata di alta qualità],70,13
15,Quanto sei d’accordo con le seguenti affermazioni? [L'esperienza di visita mi ha fatto sentire accolto/a],70,13
16,Quanto sei d’accordo con le seguenti affermazioni? [Gli spazi sono stati chiari e accessibili],70,13
17,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza è stata autentica],70,13
18,Quanto sei d’accordo con le seguenti affermazioni? [Le attività mi hanno aiutato a comprendere il territorio],70,13
19,Quanto sei d’accordo con le seguenti affermazioni? [Ho imparato qualcosa di nuovo],70,13
20,"Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza culturale mi ha coinvolto/a, non solo come spettatore/trice]",70,13
21,Quanto sei d’accordo con le seguenti affermazioni? [Le storie e i luoghi mi hanno colpito emotivamente],70,13
22,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto riflettere],70,13
23,Quanto sei d’accordo con le seguenti affermazioni? [Ho rispettato i luoghi e le persone],70,13
24,Quanto sei d’accordo con le seguenti affermazioni? [Sono stato/a attento/a all’impatto delle mie azioni],70,13
25,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha reso più consapevole del valore del territorio],70,13
26,Quanto sei d’accordo con le seguenti affermazioni? [Mi sentirei responsabile nel tornare come visitatore],70,13
27,Quanto sei d’accordo con le seguenti affermazioni? [Ho interagito con persone del luogo],70,13
28,Quanto sei d’accordo con le seguenti affermazioni? [Ho utilizzato servizi o prodotti locali],70,13
29,Quanto sei d’accordo con le seguenti affermazioni? [Sento di aver contribuito positivamente al territorio],70,13
30,Quanto sei d’accordo con le seguenti affermazioni? [Consiglierei questa esperienza ad altri],70,13
31,Quanto sei d’accordo con le seguenti affermazioni? [Tornerei o rimarrei più a lungo],69,14
32,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto stare bene],70,13
33,Quanto sei d’accordo con le seguenti affermazioni? [Mi sono sentito/a rilassato/a e stimolato/a],70,13
34,Quanto sei d’accordo con le seguenti affermazioni? [Ho vissuto un senso di connessione con il luogo],70,13
35,Quanto sei d’accordo con le seguenti affermazioni? [Questa esperienza ha arricchito il mio tempo],70,13
36,Quanto sei d’accordo con le seguenti affermazioni? [Me ne vado con una sensazione positiva],70,13
37,"Durante la tua permanenza, quanto hai speso complessivamente o prevedi di spendere (includendo alloggio, ristorazione, acquisti, trasporti e attività)?",70,13
38,Cosa ti ha colpito di più di questa esperienza e perché?,10,73
39,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]",83,0
40,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]",83,0
41,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]",83,0
42,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]",83,0
43,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]",83,0
44,Genere,68,15
45,Età:,68,15
46,Titolo di studio,68,15
47,Professione,68,15
48,Professione [Altro],1,82
49,Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?,68,15
50,Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?,3,80

### Rimozione delle colonne non pertinenti e tecniche

Dal DataFrame dei turisti vengono eliminate:

* le cinque colonne relative al cambiamento del valore patrimoniale, rivolte al gruppo dei residenti;
* le variabili tecniche generate dal sistema di raccolta;
* la domanda utilizzata per suddividere il campione, poiché tutti i partecipanti presenti in questo DataFrame appartengono già al gruppo dei non residenti.

L’identificativo della risposta viene conservato per permettere eventuali controlli sui singoli questionari.

In [29]:
# Colonne tecniche che non servono per l'analisi
colonne_tecniche_turisti = [
    "Data invio",
    "Ultima pagina",
    "Lingua iniziale",
    "Seme",
    "Data di inizio",
    "Data dell'ultima azione",
    colonna_residenza
]

# Individuo le colonne sul cambiamento del patrimonio,
# che appartengono al questionario dei residenti
colonne_patrimonio = [
    colonna
    for colonna in df_turisti_pulito.columns
    if colonna.startswith(
        "A seguito degli investimenti realizzati con il progetto Metroborgo, "
        "ritieni che il valore del tuo patrimonio"
    )
]

# Riunisco tutte le colonne da eliminare
colonne_da_eliminare = colonne_tecniche_turisti + colonne_patrimonio

# Mantengo solamente quelle effettivamente presenti
colonne_da_eliminare = [
    colonna
    for colonna in colonne_da_eliminare
    if colonna in df_turisti_pulito.columns
]

# Elimino le colonne dalla copia pulita
df_turisti_pulito = df_turisti_pulito.drop(
    columns=colonne_da_eliminare
).copy()

print("Colonne eliminate:", len(colonne_da_eliminare))
print("Dimensioni del DataFrame pulito:", df_turisti_pulito.shape)

Colonne eliminate: 12
Dimensioni del DataFrame pulito: (83, 39)

### Verifica del livello di completamento dei questionari

Per ogni questionario viene calcolato il numero di risposte effettivamente compilate.
L’identificativo della risposta viene escluso dal conteggio, perché non rappresenta una domanda del questionario.

Questo controllo permette di individuare i questionari completi, parziali o quasi vuoti prima di decidere se eliminare qualche riga.

In [30]:
# Seleziono solamente le colonne contenenti le domande
colonne_analisi_turisti = [
    colonna
    for colonna in df_turisti_pulito.columns
    if colonna != "ID risposta"
]

# Calcolo, per ogni questionario, quante risposte sono state compilate
completamento_turisti = pd.DataFrame({
    "ID risposta": df_turisti_pulito["ID risposta"],
    "Risposte compilate": df_turisti_pulito[
        colonne_analisi_turisti
    ].notna().sum(axis=1)
})

# Calcolo anche il numero di risposte mancanti
completamento_turisti["Risposte mancanti"] = (
    len(colonne_analisi_turisti)
    - completamento_turisti["Risposte compilate"]
)

# Ordino dai questionari meno completi ai più completi
completamento_turisti = completamento_turisti.sort_values(
    by="Risposte compilate"
)

completamento_turisti

    ID risposta  Risposte compilate  Risposte mancanti
0            34                   0                 38
1            43                   0                 38
2            78                   0                 38
3            89                   0                 38
4            92                   0                 38
5           112                   0                 38
60          195                   0                 38
70          209                   0                 38
80          222                   0                 38
69          207                   0                 38
71          210                   0                 38
7           120                   5                 33
63          199                   5                 33
68          205                  29                  9
81          223                  31                  7
10          132                  34                  4
24          156                  34                  4
25          157                  34                  4
26          158                  34                  4
27          159                  34                  4
28          162                  34                  4
21          153                  34                  4
22          154                  34                  4
23          155                  34                  4
29          163                  34                  4
58          193                  34                  4
14          144                  34                  4
20          152                  34                  4
19          151                  34                  4
18          150                  34                  4
15          147                  34                  4
11          134                  34                  4
50          185                  34                  4
49          183                  34                  4
53          188                  34                  4
54          189                  34                  4
55          190                  34                  4
59          194                  34                  4
62          198                  34                  4
76          218                  34                  4
74          215                  34                  4
64          200                  34                  4
56          191                  34                  4
57          192                  34                  4
51          186                  34                  4
52          187                  34                  4
17          149                  34                  4
16          148                  34                  4
75          217                  34                  4
73          214                  34                  4
72          212                  34                  4
79          221                  34                  4
77          219                  34                  4
78          220                  34                  4
39          173                  35                  3
30          164                  35                  3
47          181                  35                  3
46          180                  35                  3
45          179                  35                  3
44          178                  35                  3
43          177                  35                  3
31          165                  35                  3
32          166                  35                  3
33          167                  35                  3
40          174                  35                  3
41          175                  35                  3
42          176                  35                  3
35          169                  35                  3
36          170                  35                  3
37          171                  35                  3
38          172                  35                  3
34          168                  35                  3
67          204                  35                  3
66          203                  36                  2
13          139                  36                  2
61          197                  36                  2
9           128                  36                  2
12          136                  36                  2
6           117                  36                  2
48          182                  36                  2
82          224                  36                  2
65          202                  36                  2
8           123                  37                  1

### Rimozione dei questionari privi di risposte

Sono stati individuati 11 questionari che non contengono alcuna risposta alle domande utili per l’analisi dei turisti.

Questi questionari vengono esclusi, mentre le compilazioni parziali vengono conservate per una successiva valutazione.

In [31]:
# Individuo le righe senza alcuna risposta alle domande analitiche
indici_questionari_vuoti = completamento_turisti[
    completamento_turisti["Risposte compilate"] == 0
].index

print("Questionari completamente vuoti:",
      len(indici_questionari_vuoti))

# Elimino solamente i questionari senza risposte
df_turisti_pulito = (
    df_turisti_pulito
    .drop(index=indici_questionari_vuoti)
    .reset_index(drop=True)
)

print("Dimensioni aggiornate:",
      df_turisti_pulito.shape)

Questionari completamente vuoti: 11
Dimensioni aggiornate: (72, 39)

### Controllo dei questionari compilati solo parzialmente

Dopo la rimozione dei questionari completamente vuoti, vengono esaminate le compilazioni che contengono solamente cinque risposte.

Questo controllo permette di verificare quali sezioni siano state compilate e di decidere se conservare o escludere i questionari dall’analisi.

In [32]:
# Individuo i questionari che avevano solamente 5 risposte compilate
id_questionari_parziali = [120, 199]

# Seleziono i due questionari
questionari_parziali = df_turisti_pulito[
    df_turisti_pulito["ID risposta"].isin(id_questionari_parziali)
]

# Per ogni questionario mostro solamente le colonne compilate
for _, riga in questionari_parziali.iterrows():
    print("\n" + "=" * 70)
    print("ID risposta:", riga["ID risposta"])
    print("=" * 70)

    risposte_presenti = riga.dropna()

    for colonna, risposta in risposte_presenti.items():
        if colonna != "ID risposta":
            print(f"\n{colonna}")
            print("Risposta:", risposta)

======================================================================
ID risposta: 120
======================================================================

È la tua prima visita a Montalto delle Marche?
Risposta: No

Che tipo di visita hai o stai realizzando?
Risposta: Lunga permanenza

Qual'è il motivo principale della tua visita?
Risposta: tempo libero

Con chi hai visitato Montalto delle Marche?
Risposta: con parenti

Hai partecipato ad eventi?
Risposta: No

======================================================================
ID risposta: 199
======================================================================

È la tua prima visita a Montalto delle Marche?
Risposta: Sì

Che tipo di visita hai o stai realizzando?
Risposta: Giornata

Qual'è il motivo principale della tua visita?
Risposta: lavoro

Con chi hai visitato Montalto delle Marche?
Risposta: da solo

Hai partecipato ad eventi?
Risposta: Sì

### Controllo delle risposte aperte

Le risposte testuali vengono esaminate prima dell’analisi per individuare eventuali questionari di prova, compilazioni non valide o annotazioni che richiedano l’esclusione di una risposta.

Ogni commento viene visualizzato insieme all’identificativo del questionario.

In [33]:
# Colonne contenenti le risposte aperte
colonne_commenti = [
    "Cosa ti ha colpito di più di questa esperienza e perché?",
    "Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?"
]

# Seleziono i questionari che contengono almeno un commento
commenti_turisti = df_turisti_pulito.loc[
    df_turisti_pulito[colonne_commenti].notna().any(axis=1),
    ["ID risposta"] + colonne_commenti
]

# Stampo i commenti senza abbreviazioni
for _, riga in commenti_turisti.iterrows():
    print("\n" + "=" * 70)
    print("ID risposta:", riga["ID risposta"])

    for colonna in colonne_commenti:
        if pd.notna(riga[colonna]):
            print(f"\n{colonna}")
            print(riga[colonna])

======================================================================
ID risposta: 117

Cosa ti ha colpito di più di questa esperienza e perché?
The historical value of the city, the spectacular views in the area, the hospitality and good explanation

======================================================================
ID risposta: 123

Cosa ti ha colpito di più di questa esperienza e perché?
Sono qui a Porchia a Villa Cerqueto con mia moglie e una copia di amici. Quello che mi ha colpito di più è la gentilezza, la cortesia e la semplicità con la quale siamo stati accolti. E non parlo solo della location di Villa Cerqueto, ma anche di Marika dell’infopoint di Montalto, del Maccelaio, dei due bar che ho frequentato, del forno, di Giuseppe della cantina vini, di Marisa dove abbiamo acquistato olio, ecc….. insomma non ho trovato nessuno che mi abbia rivolto la parola tanto per vendermi quello che chiedevo, qui ogni contatto è stato un’ immersione nel vostro mondo.  Bellissima terra, bellissima gente….. sicuramente ci tornerò!

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Vorrei solo ringraziarvi tutti per avermi permesso un bellissimo soggiorno nella vostra terra

======================================================================
ID risposta: 128

Cosa ti ha colpito di più di questa esperienza e perché?
da non considerare. prova sara

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
da non considerare, prova sara

======================================================================
ID risposta: 136

Cosa ti ha colpito di più di questa esperienza e perché?
Il bar medyn perché accogliente

======================================================================
ID risposta: 139

Cosa ti ha colpito di più di questa esperienza e perché?
Comprensione della gente del posto nei tempi di attesa dei lavori di costruzione che rallentano la viabilità

======================================================================
ID risposta: 182

Cosa ti ha colpito di più di questa esperienza e perché?
il territorio

======================================================================
ID risposta: 197

Cosa ti ha colpito di più di questa esperienza e perché?
la qualità delle opere d'arte conservate nella città, in particolare le reliquiario

======================================================================
ID risposta: 202

Cosa ti ha colpito di più di questa esperienza e perché?
Trasformare un territorio è avere cura della sua memoria

======================================================================
ID risposta: 203

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Bravi

======================================================================
ID risposta: 223

Cosa ti ha colpito di più di questa esperienza e perché?
L’impegno culturale e la coesione tra le persone. L’arte aiuta a vedere le cose in modo diverso e a relazionarci con gli altri in modo più empatico

======================================================================
ID risposta: 224

Cosa ti ha colpito di più di questa esperienza e perché?
Gli eventi vissuti mi hanno aiutata a evadere dalla mia routine quotidiana e a creare uno spazio per me per confrontarmi con altri poeti di tutta Italia. Ringrazio organizzatori, città, sindaco e tutti coloro che hanno reso possibile queste splendide giornate

### Esclusione di un questionario di prova

La risposta con identificativo 128 contiene esplicitamente l’indicazione “da non considerare” e risulta essere una compilazione di prova.

Il questionario viene pertanto escluso dal DataFrame dei turisti e da tutte le successive analisi.

In [34]:
# ID del questionario di prova
id_da_escludere = [128]

# Escludo il questionario dal DataFrame generale dei turisti
df_turisti_pulito = df_turisti_pulito[
    ~df_turisti_pulito["ID risposta"].isin(id_da_escludere)
].copy()

df_turisti_pulito.reset_index(drop=True, inplace=True)

print("Questionari turistici rimasti:", len(df_turisti_pulito))

Questionari turistici rimasti: 71

# ID del questionario di prova
id_da_escludere = [128]

# Escludo il questionario dal DataFrame generale dei turisti
df_turisti_pulito = df_turisti_pulito[
    ~df_turisti_pulito["ID risposta"].isin(id_da_escludere)
].copy()

df_turisti_pulito.reset_index(drop=True, inplace=True)

print("Questionari turistici rimasti:", len(df_turisti_pulito))

In [35]:
# Questionari incompleti da escludere
id_questionari_incompleti = [120, 199]

# Elimino i questionari dal DataFrame dei turisti
df_turisti_pulito = df_turisti_pulito[
    ~df_turisti_pulito["ID risposta"].isin(
        id_questionari_incompleti
    )
].copy()

# Reimposto l'indice
df_turisti_pulito.reset_index(drop=True, inplace=True)

# Controllo il risultato finale
print("Questionari turistici validi:",
      len(df_turisti_pulito))

print("Dimensioni del DataFrame:",
      df_turisti_pulito.shape)

Questionari turistici validi: 69
Dimensioni del DataFrame: (69, 39)

## Profilo sociodemografico dei visitatori

In questa sezione viene descritta la composizione del campione turistico attraverso quattro variabili:

* genere;
* fascia d’età;
* titolo di studio;
* professione.

Per ogni variabile vengono calcolati il numero di rispondenti e la percentuale sul totale delle risposte valide.

In [36]:
# Variabili sociodemografiche da analizzare
variabili_profilo = [
    "Genere",
    "Età:",
    "Titolo di studio",
    "Professione"
]

# Funzione per creare una tabella con conteggi e percentuali
def tabella_percentuali(dataframe, colonna):
    tabella = (
        dataframe[colonna]
        .dropna()
        .value_counts()
        .rename_axis(colonna)
        .reset_index(name="Numero di risposte")
    )

    tabella["Percentuale"] = (
        tabella["Numero di risposte"]
        / tabella["Numero di risposte"].sum()
        * 100
    ).round(1)

    return tabella

# Creo e mostro una tabella per ogni variabile
for variabile in variabili_profilo:
    print("\n" + "=" * 70)
    print(variabile.upper())
    print("=" * 70)

    display(
        tabella_percentuali(
            df_turisti_pulito,
            variabile
        )
    )

======================================================================
GENERE
======================================================================

        Genere  Numero di risposte  Percentuale
0      Maschio                  38         56.7
1      Femmina                  28         41.8
2  Non binario                   1          1.5

======================================================================
ETÀ:
======================================================================

    Età:  Numero di risposte  Percentuale
0  18–30                  24         35.8
1  31–45                  19         28.4
2  46–65                  16         23.9
3    >65                   8         11.9

======================================================================
TITOLO DI STUDIO
======================================================================

,Titolo di studio,Numero di risposte,Percentuale
0,Licenza Superiore,23,34.3
1,Laurea Triennale,18,26.9
2,Laurea Magistrale / Laurea Vecchio Ordinamento,17,25.4
3,Licenza Media,7,10.4
4,Specializzazione Post-Laurea,1,1.5
5,Dottorato di Ricerca,1,1.5

======================================================================
PROFESSIONE
======================================================================

                    Professione  Numero di risposte  Percentuale
0  Lavoro a tempo indeterminato                  37         55.2
1          Studente/studentessa                   9         13.4
2                  Pensionato/a                   8         11.9
3       Libero/a professionista                   8         11.9
4    Lavoro a tempo determinato                   2          3.0
5  Imprenditore / imprenditrice                   2          3.0
6                         Altro                   1          1.5

## Caratteristiche della visita

In questa sezione vengono analizzate le principali caratteristiche della visita a Montalto delle Marche.

L’analisi considera:

* se si tratta della prima visita;
* la durata o tipologia della permanenza;
* il motivo principale della visita;
* le persone con cui è stata effettuata la visita;
* la partecipazione agli eventi.

Per ogni domanda vengono presentati il numero di risposte e la relativa percentuale, calcolata sul totale delle risposte valide.

In [37]:
# Variabili relative alle caratteristiche della visita
variabili_visita = [
    "È la tua prima visita a Montalto delle Marche?",
    "Che tipo di visita hai o stai realizzando?",
    "Qual'è il motivo principale della tua visita?",
    "Con chi hai visitato Montalto delle Marche?",
    "Hai partecipato ad eventi?"
]

# Creo e mostro una tabella per ogni variabile
for variabile in variabili_visita:
    print("\n" + "=" * 70)
    print(variabile.upper())
    print("=" * 70)

    display(
        tabella_percentuali(
            df_turisti_pulito,
            variabile
        )
    )

======================================================================
È LA TUA PRIMA VISITA A MONTALTO DELLE MARCHE?
======================================================================

,È la tua prima visita a Montalto delle Marche?,Numero di risposte,Percentuale
0,No,40,58.0
1,Sì,29,42.0

======================================================================
CHE TIPO DI VISITA HAI O STAI REALIZZANDO?
======================================================================

  Che tipo di visita hai o stai realizzando?  Numero di risposte  Percentuale
0                                   Giornata                  61         88.4
1                                    Weekend                   5          7.2
2                           Lunga permanenza                   3          4.3

======================================================================
QUAL'È IL MOTIVO PRINCIPALE DELLA TUA VISITA?
======================================================================

,Qual'è il motivo principale della tua visita?,Numero di risposte,Percentuale
0,tempo libero,59,85.5
1,lavoro,10,14.5

======================================================================
CON CHI HAI VISITATO MONTALTO DELLE MARCHE?
======================================================================

  Con chi hai visitato Montalto delle Marche?  Numero di risposte  Percentuale
0                                   con amici                  41         59.4
1                                 con parenti                  24         34.8
2                                     da solo                   4          5.8

======================================================================
HAI PARTECIPATO AD EVENTI?
======================================================================

  Hai partecipato ad eventi?  Numero di risposte  Percentuale
0                         No                  35         50.7
1                         Sì                  34         49.3

## Valutazione dell’esperienza turistica

In questa sezione vengono analizzate le affermazioni relative alla qualità e agli effetti percepiti dell’esperienza di visita.

Le risposte sono espresse su una scala da 1 a 7. Per ogni affermazione vengono calcolati:

* il numero di risposte valide;
* il punteggio medio;
* la mediana;
* la percentuale di valutazioni positive, corrispondenti ai punteggi compresi tra 5 e 7.

Valori medi più elevati indicano una percezione maggiormente positiva dell’esperienza.

In [38]:
# Individuo le colonne contenenti le valutazioni su scala da 1 a 7
colonne_valutazioni = [
    colonna
    for colonna in df_turisti_pulito.columns
    if colonna.startswith(
        "Quanto sei d’accordo con le seguenti affermazioni?"
    )
]

# Creo una tabella riepilogativa
riepilogo_valutazioni = []

for colonna in colonne_valutazioni:
    risposte = pd.to_numeric(
        df_turisti_pulito[colonna],
        errors="coerce"
    ).dropna()

    # Estraggo solamente il testo dell'affermazione tra parentesi quadre
    affermazione = colonna.split("[", 1)[-1].rstrip("]")

    riepilogo_valutazioni.append({
        "Affermazione": affermazione,
        "Risposte valide": len(risposte),
        "Media": risposte.mean(),
        "Mediana": risposte.median(),
        "Valutazioni positive (%)": (
            risposte.ge(5).mean() * 100
        )
    })

riepilogo_valutazioni = pd.DataFrame(
    riepilogo_valutazioni
)

# Arrotondo i risultati
riepilogo_valutazioni["Media"] = (
    riepilogo_valutazioni["Media"].round(2)
)

riepilogo_valutazioni["Mediana"] = (
    riepilogo_valutazioni["Mediana"].round(1)
)

riepilogo_valutazioni["Valutazioni positive (%)"] = (
    riepilogo_valutazioni[
        "Valutazioni positive (%)"
    ].round(1)
)

# Ordino dalla valutazione media più alta alla più bassa
riepilogo_valutazioni = (
    riepilogo_valutazioni
    .sort_values("Media", ascending=False)
    .reset_index(drop=True)
)

riepilogo_valutazioni

,Affermazione,Risposte valide,Media,Mediana,Valutazioni positive (%)
0,Ho rispettato i luoghi e le persone,69,6.51,7.0,94.2
1,Sono stato/a attento/a all’impatto delle mie azioni,69,6.35,7.0,95.7
2,Mi sentirei responsabile nel tornare come visitatore,69,6.23,7.0,94.2
3,Me ne vado con una sensazione positiva,69,6.10,6.0,91.3
4,L’esperienza mi ha fatto stare bene,69,6.09,6.0,89.9
5,Ho interagito con persone del luogo,69,6.03,6.0,88.4
6,Ho utilizzato servizi o prodotti locali,69,5.97,7.0,85.5
7,Mi sono sentito/a rilassato/a e stimolato/a,69,5.93,6.0,84.1
8,Consiglierei questa esperienza ad altri,69,5.80,6.0,84.1
9,Gli spazi sono stati chiari e accessibili,69,5.65,6.0,87.0
10,Questa esperienza ha arricchito il mio tempo,69,5.57,6.0,79.7
11,L'esperienza di visita mi ha fatto sentire accolto/a,69,5.48,6.0,79.7
12,Tornerei o rimarrei più a lungo,68,5.35,6.0,75.0
13,L’esperienza complessiva è stata di alta qualità,69,5.28,6.0,69.6
14,L’esperienza mi ha reso più consapevole del valore del territorio,69,5.03,6.0,65.2
15,Ho vissuto un senso di connessione con il luogo,69,4.86,5.0,55.1
16,L’esperienza è stata autentica,69,4.84,5.0,62.3
17,Sento di aver contribuito positivamente al territorio,69,4.32,4.0,47.8
18,Le storie e i luoghi mi hanno colpito emotivamente,69,4.17,4.0,49.3
19,Le attività mi hanno aiutato a comprendere il territorio,69,4.12,4.0,40.6
20,"L’esperienza culturale mi ha coinvolto/a, non solo come spettatore/trice",69,4.03,4.0,34.8
21,Ho imparato qualcosa di nuovo,69,3.88,4.0,39.1
22,L’esperienza mi ha fatto riflettere,69,3.75,4.0,36.2

### Sintesi delle valutazioni per area tematica

Le singole affermazioni vengono raggruppate in dimensioni tematiche, così da ottenere una lettura più sintetica dell’esperienza turistica.

Le aree considerate riguardano la qualità e l’accoglienza, il coinvolgimento culturale, la responsabilità verso il territorio, la relazione con il luogo e il benessere percepito.

Per ogni area viene calcolato il punteggio medio ottenuto dalle affermazioni che la compongono.

In [39]:
# Associo a ogni area le relative affermazioni
aree_valutazione = {
    "Qualità e accoglienza": [
        "L’esperienza complessiva è stata di alta qualità",
        "L'esperienza di visita mi ha fatto sentire accolto/a",
        "Gli spazi sono stati chiari e accessibili",
        "L’esperienza è stata autentica"
    ],

    "Apprendimento e coinvolgimento culturale": [
        "Le attività mi hanno aiutato a comprendere il territorio",
        "Ho imparato qualcosa di nuovo",
        "L’esperienza culturale mi ha coinvolto/a, non solo come spettatore/trice",
        "Le storie e i luoghi mi hanno colpito emotivamente",
        "L’esperienza mi ha fatto riflettere"
    ],

    "Responsabilità e sostenibilità": [
        "Ho rispettato i luoghi e le persone",
        "Sono stato/a attento/a all’impatto delle mie azioni",
        "L’esperienza mi ha reso più consapevole del valore del territorio",
        "Mi sentirei responsabile nel tornare come visitatore",
        "Sento di aver contribuito positivamente al territorio"
    ],

    "Relazione con il territorio": [
        "Ho interagito con persone del luogo",
        "Ho utilizzato servizi o prodotti locali",
        "Ho vissuto un senso di connessione con il luogo"
    ],

    "Benessere e intenzione di ritorno": [
        "Consiglierei questa esperienza ad altri",
        "Tornerei o rimarrei più a lungo",
        "L’esperienza mi ha fatto stare bene",
        "Mi sono sentito/a rilassato/a e stimolato/a",
        "Questa esperienza ha arricchito il mio tempo",
        "Me ne vado con una sensazione positiva"
    ]
}

# Uso la tabella già calcolata per ricavare la media di ogni area
riepilogo_aree = []

for area, affermazioni in aree_valutazione.items():
    dati_area = riepilogo_valutazioni[
        riepilogo_valutazioni["Affermazione"].isin(affermazioni)
    ]

    riepilogo_aree.append({
        "Area tematica": area,
        "Numero di affermazioni": len(dati_area),
        "Punteggio medio": dati_area["Media"].mean(),
        "Valutazioni positive (%)":
            dati_area["Valutazioni positive (%)"].mean()
    })

riepilogo_aree = pd.DataFrame(riepilogo_aree)

riepilogo_aree["Punteggio medio"] = (
    riepilogo_aree["Punteggio medio"].round(2)
)

riepilogo_aree["Valutazioni positive (%)"] = (
    riepilogo_aree["Valutazioni positive (%)"].round(1)
)

riepilogo_aree = riepilogo_aree.sort_values(
    "Punteggio medio",
    ascending=False
).reset_index(drop=True)

riepilogo_aree

,Area tematica,Numero di affermazioni,Punteggio medio,Valutazioni positive (%)
0,Benessere e intenzione di ritorno,6,5.81,84.0
1,Responsabilità e sostenibilità,5,5.69,79.4
2,Relazione con il territorio,3,5.62,76.3
3,Qualità e accoglienza,4,5.31,74.6
4,Apprendimento e coinvolgimento culturale,5,3.99,40.0

### Distribuzione dei visitatori per fascia di spesa

La spesa dichiarata viene rappresentata considerando tutte le fasce previste dal questionario. Anche le categorie che non hanno ricevuto risposte vengono mantenute nella tabella, così da facilitare il confronto con le rilevazioni future.

In [41]:
# Ordine completo delle fasce di spesa
fasce_spesa = [
    "Meno di 100 €",
    "Tra 100 € e 250 €",
    "Tra 250 € e 500 €",
    "Tra 500 € e 1.000 €",
    "Oltre 1.000 €"
]

# Conteggio delle risposte, includendo anche le fasce con valore zero
conteggio_spesa = (
    df_turisti_pulito[colonna_spesa]
    .value_counts()
    .reindex(fasce_spesa, fill_value=0)
)

# Creo la tabella riepilogativa
tabella_spesa = conteggio_spesa.reset_index()
tabella_spesa.columns = [
    "Fascia di spesa",
    "Numero di risposte"
]

# Calcolo le percentuali sul totale delle risposte valide
tabella_spesa["Percentuale"] = (
    tabella_spesa["Numero di risposte"]
    / tabella_spesa["Numero di risposte"].sum()
    * 100
).round(1)

tabella_spesa

       Fascia di spesa  Numero di risposte  Percentuale
0        Meno di 100 €                  65         94.2
1    Tra 100 € e 250 €                   0          0.0
2    Tra 250 € e 500 €                   0          0.0
3  Tra 500 € e 1.000 €                   0          0.0
4        Oltre 1.000 €                   4          5.8

### Controllo delle risposte con spesa superiore a 1.000 euro

Le quattro risposte appartenenti alla fascia di spesa più alta vengono esaminate singolarmente, confrontandole con le caratteristiche della visita.

Questo controllo serve a verificare se gli importi dichiarati siano plausibili oppure se possano derivare da errori di compilazione.

In [42]:
# Seleziono i questionari con spesa dichiarata superiore a 1.000 euro
spese_elevate = df_turisti_pulito[
    df_turisti_pulito[colonna_spesa] == "Oltre 1.000 €"
].copy()

# Colonne utili per verificare la coerenza delle risposte
colonne_controllo_spesa = [
    "ID risposta",
    "È la tua prima visita a Montalto delle Marche?",
    "Che tipo di visita hai o stai realizzando?",
    "Qual'è il motivo principale della tua visita?",
    "Con chi hai visitato Montalto delle Marche?",
    "Hai partecipato ad eventi?",
    colonna_spesa,
    "Professione",
    "Cosa ti ha colpito di più di questa esperienza e perché?",
    "Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?"
]

# Mantengo solo le colonne effettivamente presenti
colonne_controllo_spesa = [
    colonna
    for colonna in colonne_controllo_spesa
    if colonna in spese_elevate.columns
]

# Visualizzo le quattro risposte
spese_elevate[colonne_controllo_spesa]

,ID risposta,È la tua prima visita a Montalto delle Marche?,Che tipo di visita hai o stai realizzando?,Qual'è il motivo principale della tua visita?,Con chi hai visitato Montalto delle Marche?,Hai partecipato ad eventi?,"Durante la tua permanenza, quanto hai speso complessivamente o prevedi di spendere (includendo alloggio, ristorazione, acquisti, trasporti e attività)?",Professione,Cosa ti ha colpito di più di questa esperienza e perché?,Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
0,117,No,Lunga permanenza,tempo libero,con parenti,Sì,Oltre 1.000 €,Lavoro a tempo indeterminato,"The historical value of the city, the spectacular views in the area, the hospitality and good explanation",NaN
1,123,Sì,Lunga permanenza,tempo libero,con amici,Sì,Oltre 1.000 €,Pensionato/a,"Sono qui a Porchia a Villa Cerqueto con mia moglie e una copia di amici. Quello che mi ha colpito di più è la gentilezza, la cortesia e la semplicità con la quale siamo stati accolti. E non parlo solo della location di Villa Cerqueto, ma anche di Marika dell’infopoint di Montalto, del Maccelaio, dei due bar che ho frequentato, del forno, di Giuseppe della cantina vini, di Marisa dove abbiamo acquistato olio, ecc….. insomma non ho trovato nessuno che mi abbia rivolto la parola tanto per vendermi quello che chiedevo, qui ogni contatto è stato un’ immersione nel vostro mondo. Bellissima terra, bellissima gente….. sicuramente ci tornerò!",Vorrei solo ringraziarvi tutti per avermi permesso un bellissimo soggiorno nella vostra terra
2,132,Sì,Lunga permanenza,tempo libero,con parenti,No,Oltre 1.000 €,Lavoro a tempo indeterminato,NaN,NaN
5,139,No,Giornata,lavoro,con amici,Sì,Oltre 1.000 €,Lavoro a tempo indeterminato,Comprensione della gente del posto nei tempi di attesa dei lavori di costruzione che rallentano la viabilità,NaN

## Percezione della visibilità di Montalto delle Marche

In questa sezione viene analizzata la percezione dei visitatori rispetto al contributo del progetto Metroborgo alla visibilità nazionale e internazionale di Montalto delle Marche.

I risultati rappresentano le opinioni espresse dai partecipanti e non una misurazione oggettiva dell’effettivo aumento della visibilità del territorio.

In [43]:
# Domanda relativa alla visibilità di Montalto delle Marche
colonna_visibilita = (
    "Credi che il progetto Metroborgo abbia contribuito a migliorare "
    "la visibilità nazionale e internazionale di Montalto delle Marche?"
)

# Calcolo numero di risposte e percentuali
tabella_visibilita = tabella_percentuali(
    df_turisti_pulito,
    colonna_visibilita
)

tabella_visibilita

,Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?,Numero di risposte,Percentuale
0,No,44,65.7
1,Sì,23,34.3

# Analisi del gruppo dei residenti

In questa sezione viene analizzato separatamente il gruppo composto dai residenti e dai frequentatori abituali di Montalto delle Marche.

Prima di procedere con la pulizia e l’analisi delle risposte, viene controllata la struttura del DataFrame per individuare:

* le colonne effettivamente utilizzate;
* le domande completamente vuote;
* le compilazioni parziali;
* eventuali variabili non pertinenti al gruppo dei residenti.

In [44]:
# Controllo il numero di questionari e di colonne
print("Dimensioni del DataFrame dei residenti:", df_residenti.shape)

Dimensioni del DataFrame dei residenti: (123, 87)

## Esplorazione delle colonne

Vengono visualizzati tutti gli header presenti nel DataFrame dei residenti, così da ricostruire la struttura del questionario e distinguere le domande rivolte ai residenti da quelle destinate ai visitatori.

In [45]:
# Stampo tutti gli header del DataFrame dei residenti
for numero, colonna in enumerate(df_residenti.columns, start=1):
    print(f"{numero}. {colonna}")

print("\nNumero totale di colonne:", len(df_residenti.columns))

1. ID risposta
2. Data invio
3. Ultima pagina
4. Lingua iniziale
5. Seme
6. Data di inizio
7. Data dell'ultima azione
8. Vivi a Montalto delle Marche o la frequenti abitualmente?
9. Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?
10. Quanto sei d’accordo con le seguenti affermazioni? [Sento di poter contribuire attivamente alla vita del mio territorio]
11. Quanto sei d’accordo con le seguenti affermazioni? [Quando vedo un problema o un’opportunità nel paese, penso di poter fare qualcosa]
12. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento ascoltato/a quando esprimo idee o proposte sul futuro del territorio]
13. Quanto sei d’accordo con le seguenti affermazioni? [Ho fiducia nella mia capacità di avviare o partecipare a iniziative locali]
14. Quanto sei d’accordo con le seguenti affermazioni? [Nel mio territorio le persone collaborano tra loro]
15. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento parte di una comunità]
16. Quanto sei d’accordo con le seguenti affermazioni? [C’è fiducia reciproca tra abitanti, associazioni e operatori locali]
17. Grazie alle attività del progetto Metroborgo, hai percepito un miglioramento della tua vita sociale?
18. Grazie al progetto Metroborgo hai dialogato con chi ha un background culturale differente dal tuo?
19. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento emotivamente legato/a a questo luogo]
20. Quanto sei d’accordo con le seguenti affermazioni? [Sono orgoglioso/a di vivere qui]
21. Quanto sei d’accordo con le seguenti affermazioni? [Questo territorio rappresenta una parte importante di chi sono]
22. Quanto sei d’accordo con le seguenti affermazioni? [Mi dispiacerebbe molto dover lasciare questo luogo]
23. Quanto sei d’accordo con le seguenti affermazioni? [Partecipo ad attività culturali locali (eventi, laboratori, incontri)]
24. Quanto sei d’accordo con le seguenti affermazioni? [Gli spazi culturali mi stimolano a imparare cose nuove]
25. Quanto sei d’accordo con le seguenti affermazioni? [Le attività culturali mi fanno riflettere sul presente e sul futuro del territorio]
26. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento coinvolto/a, non solo spettatore/trice]
27. Quanto sei d’accordo con le seguenti affermazioni? [La cultura ha un ruolo importante nella mia vita quotidiana]
28. Quanto sei d’accordo con le seguenti affermazioni? [Presto attenzione alla cura degli spazi pubblici]
29. Quanto sei d’accordo con le seguenti affermazioni? [Penso alle conseguenze future delle scelte fatte oggi sul territorio]
30. Quanto sei d’accordo con le seguenti affermazioni? [Nella mia vita quotidiana presto attenzione a ridurre l’impatto ambientale delle mie azioni nel territorio in cui vivo]
31. Quanto sei d’accordo con le seguenti affermazioni? [Cerco di adottare comportamenti rispettosi dell’ambiente negli spazi pubblici e culturali (rifiuti, energia, mobilità, uso delle risorse)]
32. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento soddisfatto/a della mia vita nel territorio]
33. Quanto sei d’accordo con le seguenti affermazioni? [Vivo questo luogo come un ambiente che favorisce il benessere]
34. Quanto sei d’accordo con le seguenti affermazioni? [Le relazioni sociali contribuiscono positivamente alla mia qualità della vita]
35. Quanto sei d’accordo con le seguenti affermazioni? [Vedo prospettive positive per il futuro della comunità]
36. Quanto sei d’accordo con le seguenti affermazioni? [Mi sento mentalmente ed emotivamente a mio agio qui]
37. Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?
38. Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
39. È la tua prima visita a Montalto delle Marche?
40. Che tipo di visita hai o stai realizzando?
41. Qual'è il motivo principale della tua visita?
42. Con chi hai visitato Montalto delle Marche?
43. Hai partecipato ad eventi?
44. A quale evento hai partecipato?
45. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza complessiva è stata di alta qualità]
46. Quanto sei d’accordo con le seguenti affermazioni? [L'esperienza di visita mi ha fatto sentire accolto/a]
47. Quanto sei d’accordo con le seguenti affermazioni? [Gli spazi sono stati chiari e accessibili]
48. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza è stata autentica]
49. Quanto sei d’accordo con le seguenti affermazioni? [Le attività mi hanno aiutato a comprendere il territorio]
50. Quanto sei d’accordo con le seguenti affermazioni? [Ho imparato qualcosa di nuovo]
51. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza culturale mi ha coinvolto/a, non solo come spettatore/trice]
52. Quanto sei d’accordo con le seguenti affermazioni? [Le storie e i luoghi mi hanno colpito emotivamente]
53. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto riflettere]
54. Quanto sei d’accordo con le seguenti affermazioni? [Ho rispettato i luoghi e le persone]
55. Quanto sei d’accordo con le seguenti affermazioni? [Sono stato/a attento/a all’impatto delle mie azioni]
56. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha reso più consapevole del valore del territorio]
57. Quanto sei d’accordo con le seguenti affermazioni? [Mi sentirei responsabile nel tornare come visitatore]
58. Quanto sei d’accordo con le seguenti affermazioni? [Ho interagito con persone del luogo]
59. Quanto sei d’accordo con le seguenti affermazioni? [Ho utilizzato servizi o prodotti locali]
60. Quanto sei d’accordo con le seguenti affermazioni? [Sento di aver contribuito positivamente al territorio]
61. Quanto sei d’accordo con le seguenti affermazioni? [Consiglierei questa esperienza ad altri]
62. Quanto sei d’accordo con le seguenti affermazioni? [Tornerei o rimarrei più a lungo]
63. Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto stare bene]
64. Quanto sei d’accordo con le seguenti affermazioni? [Mi sono sentito/a rilassato/a e stimolato/a]
65. Quanto sei d’accordo con le seguenti affermazioni? [Ho vissuto un senso di connessione con il luogo]
66. Quanto sei d’accordo con le seguenti affermazioni? [Questa esperienza ha arricchito il mio tempo]
67. Quanto sei d’accordo con le seguenti affermazioni? [Me ne vado con una sensazione positiva]
68. Durante la tua permanenza, quanto hai speso complessivamente o prevedi di spendere (includendo alloggio, ristorazione, acquisti, trasporti e attività)?
69. Cosa ti ha colpito di più di questa esperienza e perché?
70. A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?
71. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]
72. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]
73. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]
74. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]
75. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]
76. Come valuti il cambiamento della qualità dell’ambiente (paesaggio urbano, spazi pubblici, servizi pubblici) dopo gli investimenti realizzati con il progetto Metroborgo?
77. Nel complesso, in che misura gli investimenti realizzati dal progetto Metroborgo hanno influenzato la qualità della tua vita?
78. Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?
79. A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?
80. Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?
81. Genere
82. Età:
83. Titolo di studio
84. Professione
85. Professione [Altro]
86. Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?
87. Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?

Numero totale di colonne: 87

## Numero di risposte presenti per colonna

Per ogni colonna viene calcolato il numero di risposte presenti e il numero di valori mancanti.

Questo controllo permette di individuare le domande non pertinenti, le colonne completamente vuote e le sezioni compilate solo parzialmente.

In [46]:
# Mostro integralmente il testo delle domande
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)

# Creo una tabella con risposte presenti e mancanti
riepilogo_colonne_residenti = pd.DataFrame({
    "Colonna": df_residenti.columns,
    "Numero di risposte": df_residenti.notna().sum().values,
    "Valori mancanti": df_residenti.isna().sum().values
})

riepilogo_colonne_residenti

,Colonna,Numero di risposte,Valori mancanti
0,ID risposta,123,0
1,Data invio,71,52
2,Ultima pagina,123,0
3,Lingua iniziale,123,0
4,Seme,123,0
5,Data di inizio,123,0
6,Data dell'ultima azione,123,0
7,Vivi a Montalto delle Marche o la frequenti abitualmente?,123,0
8,Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?,82,41
9,Quanto sei d’accordo con le seguenti affermazioni? [Sento di poter contribuire attivamente alla vita del mio territorio],83,40
10,"Quanto sei d’accordo con le seguenti affermazioni? [Quando vedo un problema o un’opportunità nel paese, penso di poter fare qualcosa]",82,41
11,Quanto sei d’accordo con le seguenti affermazioni? [Mi sento ascoltato/a quando esprimo idee o proposte sul futuro del territorio],82,41
12,Quanto sei d’accordo con le seguenti affermazioni? [Ho fiducia nella mia capacità di avviare o partecipare a iniziative locali],83,40
13,Quanto sei d’accordo con le seguenti affermazioni? [Nel mio territorio le persone collaborano tra loro],82,41
14,Quanto sei d’accordo con le seguenti affermazioni? [Mi sento parte di una comunità],83,40
15,"Quanto sei d’accordo con le seguenti affermazioni? [C’è fiducia reciproca tra abitanti, associazioni e operatori locali]",83,40
16,"Grazie alle attività del progetto Metroborgo, hai percepito un miglioramento della tua vita sociale?",83,40
17,Grazie al progetto Metroborgo hai dialogato con chi ha un background culturale differente dal tuo?,83,40
18,Quanto sei d’accordo con le seguenti affermazioni? [Mi sento emotivamente legato/a a questo luogo],83,40
19,Quanto sei d’accordo con le seguenti affermazioni? [Sono orgoglioso/a di vivere qui],83,40
20,Quanto sei d’accordo con le seguenti affermazioni? [Questo territorio rappresenta una parte importante di chi sono],83,40
21,Quanto sei d’accordo con le seguenti affermazioni? [Mi dispiacerebbe molto dover lasciare questo luogo],83,40
22,"Quanto sei d’accordo con le seguenti affermazioni? [Partecipo ad attività culturali locali (eventi, laboratori, incontri)]",83,40
23,Quanto sei d’accordo con le seguenti affermazioni? [Gli spazi culturali mi stimolano a imparare cose nuove],83,40
24,Quanto sei d’accordo con le seguenti affermazioni? [Le attività culturali mi fanno riflettere sul presente e sul futuro del territorio],83,40
25,"Quanto sei d’accordo con le seguenti affermazioni? [Mi sento coinvolto/a, non solo spettatore/trice]",83,40
26,Quanto sei d’accordo con le seguenti affermazioni? [La cultura ha un ruolo importante nella mia vita quotidiana],83,40
27,Quanto sei d’accordo con le seguenti affermazioni? [Presto attenzione alla cura degli spazi pubblici],83,40
28,Quanto sei d’accordo con le seguenti affermazioni? [Penso alle conseguenze future delle scelte fatte oggi sul territorio],83,40
29,Quanto sei d’accordo con le seguenti affermazioni? [Nella mia vita quotidiana presto attenzione a ridurre l’impatto ambientale delle mie azioni nel territorio in cui vivo],83,40
30,"Quanto sei d’accordo con le seguenti affermazioni? [Cerco di adottare comportamenti rispettosi dell’ambiente negli spazi pubblici e culturali (rifiuti, energia, mobilità, uso delle risorse)]",83,40
31,Quanto sei d’accordo con le seguenti affermazioni? [Mi sento soddisfatto/a della mia vita nel territorio],83,40
32,Quanto sei d’accordo con le seguenti affermazioni? [Vivo questo luogo come un ambiente che favorisce il benessere],83,40
33,Quanto sei d’accordo con le seguenti affermazioni? [Le relazioni sociali contribuiscono positivamente alla mia qualità della vita],83,40
34,Quanto sei d’accordo con le seguenti affermazioni? [Vedo prospettive positive per il futuro della comunità],83,40
35,Quanto sei d’accordo con le seguenti affermazioni? [Mi sento mentalmente ed emotivamente a mio agio qui],83,40
36,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,82,41
37,"Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?",37,86
38,È la tua prima visita a Montalto delle Marche?,0,123
39,Che tipo di visita hai o stai realizzando?,0,123
40,Qual'è il motivo principale della tua visita?,0,123
41,Con chi hai visitato Montalto delle Marche?,0,123
42,Hai partecipato ad eventi?,0,123
43,A quale evento hai partecipato?,0,123
44,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza complessiva è stata di alta qualità],0,123
45,Quanto sei d’accordo con le seguenti affermazioni? [L'esperienza di visita mi ha fatto sentire accolto/a],0,123
46,Quanto sei d’accordo con le seguenti affermazioni? [Gli spazi sono stati chiari e accessibili],0,123
47,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza è stata autentica],0,123
48,Quanto sei d’accordo con le seguenti affermazioni? [Le attività mi hanno aiutato a comprendere il territorio],0,123
49,Quanto sei d’accordo con le seguenti affermazioni? [Ho imparato qualcosa di nuovo],0,123
50,"Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza culturale mi ha coinvolto/a, non solo come spettatore/trice]",0,123
51,Quanto sei d’accordo con le seguenti affermazioni? [Le storie e i luoghi mi hanno colpito emotivamente],0,123
52,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto riflettere],0,123
53,Quanto sei d’accordo con le seguenti affermazioni? [Ho rispettato i luoghi e le persone],0,123
54,Quanto sei d’accordo con le seguenti affermazioni? [Sono stato/a attento/a all’impatto delle mie azioni],0,123
55,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha reso più consapevole del valore del territorio],0,123
56,Quanto sei d’accordo con le seguenti affermazioni? [Mi sentirei responsabile nel tornare come visitatore],0,123
57,Quanto sei d’accordo con le seguenti affermazioni? [Ho interagito con persone del luogo],0,123
58,Quanto sei d’accordo con le seguenti affermazioni? [Ho utilizzato servizi o prodotti locali],0,123
59,Quanto sei d’accordo con le seguenti affermazioni? [Sento di aver contribuito positivamente al territorio],0,123
60,Quanto sei d’accordo con le seguenti affermazioni? [Consiglierei questa esperienza ad altri],0,123
61,Quanto sei d’accordo con le seguenti affermazioni? [Tornerei o rimarrei più a lungo],0,123
62,Quanto sei d’accordo con le seguenti affermazioni? [L’esperienza mi ha fatto stare bene],0,123
63,Quanto sei d’accordo con le seguenti affermazioni? [Mi sono sentito/a rilassato/a e stimolato/a],0,123
64,Quanto sei d’accordo con le seguenti affermazioni? [Ho vissuto un senso di connessione con il luogo],0,123
65,Quanto sei d’accordo con le seguenti affermazioni? [Questa esperienza ha arricchito il mio tempo],0,123
66,Quanto sei d’accordo con le seguenti affermazioni? [Me ne vado con una sensazione positiva],0,123
67,"Durante la tua permanenza, quanto hai speso complessivamente o prevedi di spendere (includendo alloggio, ristorazione, acquisti, trasporti e attività)?",0,123
68,Cosa ti ha colpito di più di questa esperienza e perché?,0,123
69,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?",74,49
70,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]",123,0
71,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]",123,0
72,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]",123,0
73,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]",123,0
74,"A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]",123,0
75,"Come valuti il cambiamento della qualità dell’ambiente (paesaggio urbano, spazi pubblici, servizi pubblici) dopo gli investimenti realizzati con il progetto Metroborgo?",75,48
76,"Nel complesso, in che misura gli investimenti realizzati dal progetto Metroborgo hanno influenzato la qualità della tua vita?",75,48
77,"Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?",75,48
78,"A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?",75,48
79,Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?,9,114
80,Genere,71,52
81,Età:,70,53
82,Titolo di studio,71,52
83,Professione,71,52
84,Professione [Altro],1,122
85,Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?,71,52
86,Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?,19,104

## Rimozione delle colonne non pertinenti al gruppo dei residenti

Nel DataFrame dei residenti sono presenti alcune domande rivolte esclusivamente ai visitatori.

Poiché queste colonne non contengono alcuna risposta nel gruppo analizzato, vengono eliminate. In questa fase non vengono ancora rimosse righe o compilazioni parziali.

In [47]:
# Individuo le colonne completamente vuote
colonne_vuote_residenti = df_residenti.columns[
    df_residenti.isna().all()
].tolist()

# Creo una copia eliminando soltanto le colonne completamente vuote
df_residenti_pulito = df_residenti.drop(
    columns=colonne_vuote_residenti
).copy()

print("Colonne originali:", df_residenti.shape[1])
print("Colonne completamente vuote eliminate:",
      len(colonne_vuote_residenti))
print("Colonne rimaste:", df_residenti_pulito.shape[1])
print("Dimensioni del DataFrame:",
      df_residenti_pulito.shape)

Colonne originali: 87
Colonne completamente vuote eliminate: 31
Colonne rimaste: 56
Dimensioni del DataFrame: (123, 56)

### Controllo della codifica della domanda sul patrimonio

La domanda relativa al cambiamento del valore patrimoniale è stata esportata in cinque colonne distinte, una per ciascuna possibile risposta.

Prima di procedere con la pulizia, viene verificato come sono codificati i valori presenti nelle colonne.

In [48]:
# Individuo le colonne relative al cambiamento del patrimonio
colonne_patrimonio_residenti = [
    colonna
    for colonna in df_residenti_pulito.columns
    if colonna.startswith(
        "A seguito degli investimenti realizzati con il progetto Metroborgo, "
        "ritieni che il valore del tuo patrimonio"
    )
]

print("Numero di colonne individuate:",
      len(colonne_patrimonio_residenti))

# Visualizzo i valori presenti in ogni colonna
for colonna in colonne_patrimonio_residenti:
    print("\n" + "=" * 70)
    print(colonna)
    print(df_residenti_pulito[colonna].value_counts(dropna=False))

Numero di colonne individuate: 5

======================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]
No    121
Sì      2
Name: count, dtype: int64

======================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]
No    122
Sì      1
Name: count, dtype: int64

======================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]
No    72
Sì    51
Name: count, dtype: int64

======================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]
No    104
Sì     19
Name: count, dtype: int64

======================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]
No    119
Sì      4
Name: count, dtype: int64

### Esplorazione della sezione economica

Prima di procedere con la pulizia dei dati, viene esaminata l’intera sezione del questionario dedicata agli effetti economici percepiti del progetto Metroborgo.

L’obiettivo è distinguere correttamente le domande relative a:

* cambiamento del reddito personale o familiare;
* cambiamento del valore patrimoniale;
* qualità dell’ambiente e qualità della vita;
* soddisfazione rispetto agli investimenti;
* investimenti economici effettuati dai partecipanti;
* ammontare degli investimenti dichiarati.

In questa fase non viene modificata alcuna variabile.

In [49]:
# Seleziono la sezione economica del questionario
colonne_economiche = df_residenti.columns[69:80]

# Stampo il numero originale e il nome completo di ogni colonna
for indice, colonna in enumerate(colonne_economiche, start=69):
    print(f"{indice}. {colonna}")

69. A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?
70. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]
71. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]
72. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]
73. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]
74. A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]
75. Come valuti il cambiamento della qualità dell’ambiente (paesaggio urbano, spazi pubblici, servizi pubblici) dopo gli investimenti realizzati con il progetto Metroborgo?
76. Nel complesso, in che misura gli investimenti realizzati dal progetto Metroborgo hanno influenzato la qualità della tua vita?
77. Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?
78. A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?
79. Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?

In [50]:
# Visualizzo le risposte presenti per ogni colonna economica
for colonna in colonne_economiche:
    print("\n" + "=" * 80)
    print(colonna)
    print(df_residenti[colonna].value_counts(dropna=False))

================================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?
A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?
È rimasto invariata        57
NaN                        49
È aumentato leggermente    10
È diminuito molto           3
È diminuito leggermente     3
È aumentato molto           1
Name: count, dtype: int64

================================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito molto]
No    121
Sì      2
Name: count, dtype: int64

================================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È diminuito leggermente]
No    122
Sì      1
Name: count, dtype: int64

================================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È rimasto invariato]
No    72
Sì    51
Name: count, dtype: int64

================================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato leggermente]
No    104
Sì     19
Name: count, dtype: int64

================================================================================
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]
A seguito degli investimenti realizzati con il progetto Metroborgo, ritieni che il valore del tuo patrimonio (ad esempio immobili, attività economiche, beni) sia cambiato? [È aumentato molto]
No    119
Sì      4
Name: count, dtype: int64

================================================================================
Come valuti il cambiamento della qualità dell’ambiente (paesaggio urbano, spazi pubblici, servizi pubblici) dopo gli investimenti realizzati con il progetto Metroborgo?
Come valuti il cambiamento della qualità dell’ambiente (paesaggio urbano, spazi pubblici, servizi pubblici) dopo gli investimenti realizzati con il progetto Metroborgo?
NaN                 48
Migliorata          36
Invariata           22
Molto migliorata    13
Molto peggiorata     3
Peggiorata           1
Name: count, dtype: int64

================================================================================
Nel complesso, in che misura gli investimenti realizzati dal progetto Metroborgo hanno influenzato la qualità della tua vita?
Nel complesso, in che misura gli investimenti realizzati dal progetto Metroborgo hanno influenzato la qualità della tua vita?
NaN                         48
Influenza positiva          33
Nessuna influenza           33
Influenza negativa           5
Influenza molto positiva     3
Influenza molto negativa     1
Name: count, dtype: int64

================================================================================
Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?
Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?
NaN                            48
Abbastanza soddisfatto/a       29
Molto soddisfatto/a            19
Poco soddisfatto/a             13
Completamente soddisfatto/a     8
Per niente soddisfatto/a        6
Name: count, dtype: int64

================================================================================
A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?
A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?
No     66
NaN    48
Sì      9
Name: count, dtype: int64

================================================================================
Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?
Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?
NaN                       114
Oltre 100.000 €             4
Meno di 5.000 €             4
Tra 5.000 € e 20.000 €      1
Name: count, dtype: int64

### Controllo delle risposte mancanti o multiple sul patrimonio

La domanda relativa al cambiamento del valore patrimoniale è stata esportata in cinque colonne distinte.

Il controllo mostra che:

* 73 partecipanti hanno selezionato una sola opzione;
* 48 partecipanti non hanno selezionato alcuna opzione;
* 2 partecipanti hanno selezionato due opzioni.

Prima di ricostruire una variabile unica, vengono esaminati i due questionari con risposte multiple. Le risposte mancanti verranno invece conservate come valori non disponibili.

In [51]:
# Conto quante opzioni patrimoniali risultano selezionate per ogni questionario
numero_scelte_patrimonio = (
    df_residenti_pulito[colonne_patrimonio_residenti]
    .eq("Sì")
    .sum(axis=1)
)

numero_scelte_patrimonio.value_counts().sort_index()

0    48
1    73
2     2
Name: count, dtype: int64

In [53]:
# Individuo i questionari con più di una risposta selezionata
indici_patrimonio_multiplo = numero_scelte_patrimonio[
    numero_scelte_patrimonio > 1
].index

# Seleziono i questionari interessati
risposte_patrimonio_multiple = df_residenti_pulito.loc[
    indici_patrimonio_multiplo,
    ["ID risposta"] + colonne_patrimonio_residenti
]

# Mostro soltanto le opzioni selezionate con "Sì"
for _, riga in risposte_patrimonio_multiple.iterrows():
    print("\n" + "=" * 70)
    print("ID risposta:", riga["ID risposta"])

    opzioni_selezionate = [
        colonna.split("[", 1)[-1].rstrip("]")
        for colonna in colonne_patrimonio_residenti
        if riga[colonna] == "Sì"
    ]

    for opzione in opzioni_selezionate:
        print("-", opzione)

======================================================================
ID risposta: 13
- È rimasto invariato
- È aumentato leggermente

======================================================================
ID risposta: 63
- È rimasto invariato
- È aumentato leggermente

### Ricostruzione della variabile sul valore patrimoniale

La domanda sul cambiamento del valore patrimoniale è stata esportata in cinque colonne binarie.

La nuova variabile viene ricostruita mantenendo:

* la categoria selezionata, quando è presente una sola risposta;
* un valore mancante, quando non è stata selezionata alcuna opzione;
* una categoria specifica per le due compilazioni che indicano contemporaneamente “È rimasto invariato” ed “È aumentato leggermente”.

In questo modo le risposte ambigue vengono conservate senza attribuire arbitrariamente una categoria.

In [54]:
# Funzione per ricostruire la risposta patrimoniale
def ricostruisci_patrimonio(riga):
    opzioni_selezionate = [
        colonna.split("[", 1)[-1].rstrip("]")
        for colonna in colonne_patrimonio_residenti
        if riga[colonna] == "Sì"
    ]

    # Nessuna risposta selezionata
    if len(opzioni_selezionate) == 0:
        return pd.NA

    # Una sola risposta selezionata
    if len(opzioni_selezionate) == 1:
        return opzioni_selezionate[0]

    # Più risposte selezionate
    return "Risposta multipla: " + " / ".join(opzioni_selezionate)


# Creo la nuova variabile categoriale
df_residenti_pulito["Cambiamento del valore patrimoniale"] = (
    df_residenti_pulito.apply(
        ricostruisci_patrimonio,
        axis=1
    )
)

# Controllo il risultato
df_residenti_pulito[
    "Cambiamento del valore patrimoniale"
].value_counts(dropna=False)

Cambiamento del valore patrimoniale
È rimasto invariato                                                 49
<NA>                                                                48
È aumentato leggermente                                             17
È aumentato molto                                                    4
Risposta multipla: È rimasto invariato / È aumentato leggermente     2
È diminuito molto                                                    2
È diminuito leggermente                                              1
Name: count, dtype: int64

### Rimozione delle colonne patrimoniali originali

Dopo aver ricostruito la variabile unica relativa al cambiamento del valore patrimoniale, le cinque colonne binarie originali vengono eliminate.

La nuova variabile conserva tutte le informazioni disponibili, comprese le risposte mancanti e le due compilazioni multiple.

In [55]:
# Elimino le cinque colonne binarie originali
df_residenti_pulito = df_residenti_pulito.drop(
    columns=colonne_patrimonio_residenti
).copy()

# Controllo le nuove dimensioni del DataFrame
print("Dimensioni aggiornate del DataFrame:",
      df_residenti_pulito.shape)

Dimensioni aggiornate del DataFrame: (123, 52)

### Controllo delle risposte aperte

Le risposte testuali vengono esaminate per individuare eventuali questionari di prova, annotazioni non pertinenti o compilazioni che potrebbero dover essere escluse dall’analisi.

Ogni risposta aperta viene visualizzata insieme all’identificativo del relativo questionario. In questa fase non viene eliminata alcuna riga.

In [56]:
# Colonne contenenti le risposte aperte dei residenti
colonne_aperte_residenti = [
    "Cosa ti aspetti che cambi, grazie al progetto Metroborgo, "
    "nella vita del territorio e nella tua vita personale?",
    
    "Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?"
]

# Seleziono i questionari che contengono almeno una risposta aperta
risposte_aperte_residenti = df_residenti_pulito.loc[
    df_residenti_pulito[colonne_aperte_residenti]
    .notna()
    .any(axis=1),
    ["ID risposta"] + colonne_aperte_residenti
]

# Stampo integralmente tutte le risposte
for _, riga in risposte_aperte_residenti.iterrows():
    print("\n" + "=" * 80)
    print("ID risposta:", riga["ID risposta"])

    for colonna in colonne_aperte_residenti:
        if pd.notna(riga[colonna]):
            print(f"\n{colonna}")
            print("Risposta:", riga[colonna])

================================================================================
ID risposta: 14

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Il coinvolgimento dei giovani e giovanissimi, perché il futuro è nelle loro mani. Per quanto a quell'età si desideri vedere e crescere in altri luoghi è importante creare il terreno fertile affinché una volta tornati, con il loro bagaglio pieno di esperienze, possano avere l'opportunità di vivere veramente il paese, di essere coinvolti attivamente e di restare.

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Spero che tutto ciò porti veramente a qualche cambiamento, forse però bisognerebbe partire dalla mentalità delle persone. Sicuramente più opportunità potranno scaturire un cambiamento, ma la cittadinanza attiva è una questione di partecipazione e al momento ne vedo poca. I questionari sono sicuramente un'ottima base di partenza, con la speranza che siano compilati dalla maggioranza della popolazione!

================================================================================
ID risposta: 18

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Più coinvolgimento da parte di associazioni e comunità

================================================================================
ID risposta: 19

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Incremento turistico

================================================================================
ID risposta: 22

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Coinvolgimento tra la popolazione

================================================================================
ID risposta: 23

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Che il paese possa diventare un punto di riferimento sia sociale che culturale nella provincia

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Ritengo indispensabile un intervento urgente di verifica e monitoraggio delle infrastrutture di rete in fibra ottica presenti sul territorio comunale. Oggi la connettività non è più un servizio accessorio, ma un’infrastruttura essenziale per studio, lavoro, servizi digitali e sviluppo economico locale.
Segnalo la presenza di numerosi scavi e predisposizioni per la fibra ottica già realizzati ma tuttora inutilizzati o non attivi. Tali opere, finanziate con risorse pubbliche, rappresentano di fatto un investimento bloccato e uno spreco di denaro dei cittadini, oltre a privare la comunità di un servizio fondamentale.
Chiedo pertanto che l’Amministrazione solleciti formalmente Infratel, Open Fiber e gli operatori coinvolti affinché vengano chiarite e rimosse le cause burocratiche o amministrative che impediscono l’attivazione della rete, valutando anche eventuali responsabilità per inefficienze o ritardi che possano configurare un danno erariale. È necessario garantire tempi certi e trasparenza nell’utilizzo dei fondi pubblici, evitando che infrastrutture già realizzate restino inutilizzate a discapito dei cittadini.

================================================================================
ID risposta: 25

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Che ci sia più ascolto tra cittadino e amministrazioni

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Più coinvolgimento nella cultura più coinvolgimento con i giovani più dialogo più aiuto sempre ai giovani che hanno la voglia di fare aprendo nuove attività soprattutto che riguardano il territorio prettamente agricolo informazione quindi e soprattutto economico

================================================================================
ID risposta: 27

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Mi aspetto uno scenario vivo dal punto di vista culturale, movimento di persone, di idee, di progetti, che non solo coinvolgeranno persone esterne, ma soprattutto le nuove generazioni che abitano quesyo territorio, e che potranno continuare a farlo.

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Quelle che sono al momento percezioni, diventeranno realtà.
Un enorme lavoro è stato fatto per non farci sfuggire queste opportunità, e altrettanto dovrà essere fatto in futuro per mantenere e mandare avanti i progetti pensati.
Sarà una grande sfida per le generazioni future, che devono capire ora quello che sta accadendo, per non perdere tutto nei prossimi anni.

================================================================================
ID risposta: 30

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Mi aspetto che Montalto diventi un paese vivo, in cui non manchino iniziative che coinvolgono la comunità in occasioni di incontro e arricchimento.

================================================================================
ID risposta: 31

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Purtroppo per quanto ci si impegni …molto poco ..!!


================================================================================
ID risposta: 36

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Più occasioni di incontro, conoscenza, scambio, arricchimento e crescita, riqualificazione dei luoghi (chiusi e aperti), maggior fruizione del territorio naturale... Vorrei eventi o ambienti che coinvolgessero il maggior numero di persone, non per forza 'elevati' ... es.cinema, concerti pop/rock, piccole biblioteche sparse magari tematiche .. ma già quello che si sta facendo è moltissimo!!

================================================================================
ID risposta: 39

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: In primis tanto turismo per il  paese e per la mia attività l

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: No stanno facendo tantissimo

================================================================================
ID risposta: 40

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Mi aspetto che il territorio si rivitalizzi, accolga nuovi abitanti, torni a progettare e condividere attività turistiche, culturali, economiche. Torni ad avere fiducia nel futuro e riscopra il piacere e la bellezza del fare comunita'. Nella mia vita personale spero cambino la quantità e la qualità della relazioni sociali locali

================================================================================
ID risposta: 42

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Opportunità lavorative, ripopolamento del borgo (soprattutto giovanile)

================================================================================
ID risposta: 48

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: più lavoro,piùpersone che vengono ad abitare ,più servizi ,più turismo.

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Ancora più visibilità.

================================================================================
ID risposta: 49

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Che ci sia una nuova "apertura" mentale e consapevolezza del luogo privilegiato in cui viviamo dove però mancano le risorse umane e lo scambio di relazioni che portino a una vivacità costruttiva necessaria alla formazione di una nuova coscienza collettiva.

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Alcune risposte date non sono perfettamente in linea con il mio pensiero più autentico perché i lavori sono ancora in atto e solo tra un paio di anni si potrà davvero dare un giudizio sulla base di quanto realizzato. In generale Montalto ha avuto comunque una maggiore visibilità a livello nazionale ma occorre sensibilizzare maggiormente le giovani generazioni con iniziative più mirate che facciano crescere la consapevolezza e il senso di appartenenza al territorio.

================================================================================
ID risposta: 54

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: L'aspetto sociale
,creativo
Culturale

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Si poca socializzazione come sempre

================================================================================
ID risposta: 59

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Niente.

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Secondo me questo progetto non porterà lavoro per i montaltesi e gli investimenti, se mai arriveranno a termine, porteranno profitto a gente che di fuori ammanicata con la politica.

================================================================================
ID risposta: 62

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Crescita generale e aumento popolazione e servizi

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: No

================================================================================
ID risposta: 66

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Mi aspetto che faccia crescere  paese in tutti i campi.

================================================================================
ID risposta: 73

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Rivedere il modo di gestire i rifiuti
Coinvolgere maggiormente i giovani

================================================================================
ID risposta: 74

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Incremento delle attività turistiche e opportunità lavorative

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: La diminuzione della popolazione nel territorio e il suo invecchiamento può compromettere qualsiasi progetto...anche se ben  congeniato
Forza Montalto

================================================================================
ID risposta: 83

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta:  Amo il .mio paese purtroppo non sono stimolata da una gran parte perché non ha  voglia di costruire,lavorare e magari sognare un futuro di verso! I giovani soprattutto non sanno so ializzate o.   Nono vogliono fare! .i auguro. He con il tempo capiscano che bisogna cambiare guardare al nostro territorio come un traguardo positivo per noi e per quelli che magari avranno intenzione di venire qui

================================================================================
ID risposta: 86

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Maggiore vitalità culturale, più iniziative, più socialità, più partecipazione

================================================================================
ID risposta: 88

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: È stato già molto cambiato in una cittadina come Montalto. Forse sono rimasto troppo legato alla Montalto in cui ho vissuto e che non tornerà più, anzi mi è stata cancellata, purtroppo !!! 😭😭😔😔😔

================================================================================
ID risposta: 93

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Aumento della collaborazione e dell'accettazione dell'altro nella popolazione

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Credo che una parte importante di ogni attività sia la rendicontazione come cosa pubblica

================================================================================
ID risposta: 96

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Miglioramento del clima sociale, maggiore coinvolgimento degli abitanti nella progettazione e realizzazione delle attività, maggiore partecipazione, arricchimento delle attività culturali

================================================================================
ID risposta: 99

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Opportunità per i giovani. Crescita personale e comunitaria. Opportunità per gli anziani e disabili. Iniziative davvero coinvolgenti per la comunità: luoghi di incontro, laborator, letture, scoperta del territorio, nuove realtà lavorative, capacità di operare nuovi progetti.

================================================================================
ID risposta: 109

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Nuove attività, più giovani attirati da Montalto

================================================================================
ID risposta: 113

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Purtroppo non credo o credo  poco nella possibilità di un cambiamento in seguito al progetto Metroborgo

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Alcuni investimenti inutili per il territorio

================================================================================
ID risposta: 114

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: piu afflusso di gente e piu attività per i residenti

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: nulla

================================================================================
ID risposta: 115

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: piu possibilità per le imprese

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: nulla

================================================================================
ID risposta: 127

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: QUESTIONARIO PROVA SARA

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: DA NON CONSIDERARE

================================================================================
ID risposta: 138

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Avere più visione anche nelle case in campagna , strade da sistemare !!!!! C’è ancora molto da fare .

================================================================================
ID risposta: 140

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: gli investimenti scelti non portano lavoro nel territorio e non contribuiscono allo spopolamento del territorio. Sarebbe stato meglio investire nella formazione di operai specializzati e il finanziamento di una fabbrica e outlet, il paese non può vivere di turismo.

================================================================================
ID risposta: 141

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: gli investimenti fatti non mirano a ripopolare il territorio ne portano servizi per i locali. Avrei trovato più utile un campo di bocce per i cittadini invece di un teatro all'aperto

================================================================================
ID risposta: 201

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: La sensibilità nei confronti dell' ambiente e tra le persone...

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Speriamo di crescere ancora sotto il profilo culturale.

================================================================================
ID risposta: 206

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Spero possa fare rivivere il bellissimo borgo. Spero che tutti gli sforzi fatti per portare avanti questo progetto siano fruttosi e portino benessere alla comunità montaltese.

================================================================================
ID risposta: 213

Cosa ti aspetti che cambi, grazie al progetto Metroborgo, nella vita del territorio e nella tua vita personale?
Risposta: Mi aspetto sviluppo e progresso

Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?
Risposta: Il Presidato di Montalto!

### Rimozione delle colonne tecniche

Dal DataFrame dei residenti vengono eliminate le variabili tecniche generate dal sistema di raccolta e la domanda utilizzata per suddividere il campione.

L’identificativo della risposta viene conservato per consentire eventuali controlli sui singoli questionari.

In [57]:
# Colonne tecniche non necessarie per l'analisi
colonne_tecniche_residenti = [
    "Data invio",
    "Ultima pagina",
    "Lingua iniziale",
    "Seme",
    "Data di inizio",
    "Data dell'ultima azione",
    colonna_residenza
]

# Mantengo solamente le colonne effettivamente presenti
colonne_tecniche_residenti = [
    colonna
    for colonna in colonne_tecniche_residenti
    if colonna in df_residenti_pulito.columns
]

# Elimino le colonne tecniche
df_residenti_pulito = df_residenti_pulito.drop(
    columns=colonne_tecniche_residenti
).copy()

print("Colonne tecniche eliminate:",
      len(colonne_tecniche_residenti))

print("Dimensioni aggiornate:",
      df_residenti_pulito.shape)

Colonne tecniche eliminate: 7
Dimensioni aggiornate: (123, 45)

### Verifica del livello di completamento dei questionari

Per ogni questionario viene calcolato il numero di risposte compilate nelle domande principali.

Dal conteggio vengono escluse le variabili identificative, le domande aperte e alcune domande condizionali, che possono essere legittimamente vuote.

Questo controllo permette di individuare le compilazioni completamente vuote o interrotte prima di procedere con l’analisi.

In [58]:
# Colonne da escludere dal controllo del completamento
colonne_escluse_completamento = [
    "ID risposta",
    "Cosa ti aspetti che cambi, grazie al progetto Metroborgo, "
    "nella vita del territorio e nella tua vita personale?",
    "Pensieri liberi. C’è qualcos’altro che vorresti aggiungere?",
    "Professione [Altro]",
    "Qual è stato approssimativamente l’ammontare complessivo "
    "degli investimenti effettuati?"
]

# Mantengo soltanto le colonne effettivamente presenti
colonne_escluse_completamento = [
    colonna
    for colonna in colonne_escluse_completamento
    if colonna in df_residenti_pulito.columns
]

# Individuo le colonne principali da considerare
colonne_analisi_residenti = [
    colonna
    for colonna in df_residenti_pulito.columns
    if colonna not in colonne_escluse_completamento
]

# Calcolo il numero di risposte compilate per questionario
completamento_residenti = pd.DataFrame({
    "ID risposta": df_residenti_pulito["ID risposta"],
    "Risposte compilate": (
        df_residenti_pulito[colonne_analisi_residenti]
        .notna()
        .sum(axis=1)
    )
})

# Calcolo anche il numero di risposte mancanti
completamento_residenti["Risposte mancanti"] = (
    len(colonne_analisi_residenti)
    - completamento_residenti["Risposte compilate"]
)

# Ordino dai questionari meno completi ai più completi
completamento_residenti = completamento_residenti.sort_values(
    by="Risposte compilate"
)

completamento_residenti

     ID risposta  Risposte compilate  Risposte mancanti
9             21                   0                 40
21            33                   0                 40
20            32                   0                 40
16            28                   0                 40
31            46                   0                 40
62            77                   0                 40
57            72                   0                 40
56            71                   0                 40
49            64                   0                 40
53            68                   0                 40
55            70                   0                 40
63            79                   0                 40
43            58                   0                 40
45            60                   0                 40
46            61                   0                 40
35            50                   0                 40
60            75                   0                 40
81           100                   0                 40
85           104                   0                 40
82           101                   0                 40
86           105                   0                 40
89           108                   0                 40
91           110                   0                 40
84           103                   0                 40
73            90                   0                 40
74            91                   0                 40
78            97                   0                 40
71            87                   0                 40
69            85                   0                 40
66            82                   0                 40
65            81                   0                 40
64            80                   0                 40
96           116                   0                 40
97           118                   0                 40
98           119                   0                 40
99           121                   0                 40
100          122                   0                 40
106          133                   0                 40
119          208                   0                 40
112          143                   0                 40
22            35                  27                 13
67            83                  28                 12
80            99                  28                 12
61            76                  29                 11
18            30                  29                 11
6             17                  29                 11
120          211                  29                 11
36            51                  29                 11
108          138                  34                  6
72            88                  35                  5
12            24                  35                  5
38            53                  35                  5
102          127                  38                  2
30            45                  40                  0
28            41                  40                  0
29            42                  40                  0
15            27                  40                  0
5             16                  40                  0
7             18                  40                  0
0             11                  40                  0
3             14                  40                  0
4             15                  40                  0
2             13                  40                  0
1             12                  40                  0
58            73                  40                  0
59            74                  40                  0
52            67                  40                  0
48            63                  40                  0
51            66                  40                  0
50            65                  40                  0
54            69                  40                  0
32            47                  40                  0
39            54                  40                  0
37            52                  40                  0
33            48                  40                  0
40            55                  40                  0
42            57                  40                  0
41            56                  40                  0
44            59                  40                  0
47            62                  40                  0
34            49                  40                  0
14            26                  40                  0
13            25                  40                  0
11            23                  40                  0
8             19                  40                  0
10            22                  40                  0
19            31                  40                  0
17            29                  40                  0
23            36                  40                  0
24            37                  40                  0
26            39                  40                  0
25            38                  40                  0
27            40                  40                  0
68            84                  40                  0
79            98                  40                  0
77            96                  40                  0
95           115                  40                  0
94           114                  40                  0
93           113                  40                  0
92           111                  40                  0
90           109                  40                  0
88           107                  40                  0
83           102                  40                  0
87           106                  40                  0
75            93                  40                  0
76            94                  40                  0
70            86                  40                  0
103          129                  40                  0
107          135                  40                  0
101          125                  40                  0
105          131                  40                  0
104          130                  40                  0
111          142                  40                  0
110          141                  40                  0
109          140                  40                  0
114          146                  40                  0
115          160                  40                  0
116          161                  40                  0
117          201                  40                  0
113          145                  40                  0
118          206                  40                  0
121          213                  40                  0
122          216                  40                  0

### Rimozione dei questionari privi di risposte utili

Il controllo del livello di completamento ha individuato 40 questionari che non contengono alcuna risposta alle domande principali rivolte ai residenti.

Queste righe vengono escluse dall’analisi. I questionari compilati parzialmente vengono invece conservati temporaneamente e saranno esaminati separatamente prima di decidere se utilizzarli.

In [59]:
# Individuo gli ID dei questionari senza risposte principali
id_residenti_vuoti = completamento_residenti.loc[
    completamento_residenti["Risposte compilate"] == 0,
    "ID risposta"
].tolist()

print("Questionari completamente vuoti:",
      len(id_residenti_vuoti))

# Elimino soltanto i questionari completamente vuoti
df_residenti_pulito = df_residenti_pulito[
    ~df_residenti_pulito["ID risposta"].isin(id_residenti_vuoti)
].copy()

# Reimposto l'indice del DataFrame
df_residenti_pulito.reset_index(drop=True, inplace=True)

print("Questionari residenti rimasti:",
      len(df_residenti_pulito))

print("Dimensioni aggiornate:",
      df_residenti_pulito.shape)

Questionari completamente vuoti: 40
Questionari residenti rimasti: 83
Dimensioni aggiornate: (83, 45)

### Analisi dei questionari compilati parzialmente

Dopo la rimozione dei questionari completamente vuoti, vengono esaminate le compilazioni incomplete.

Per ciascun questionario vengono indicati:

* il numero di domande principali compilate;
* l’ultima domanda alla quale è stata fornita una risposta;
* la prima domanda mancante.

Questo controllo permette di capire se il partecipante abbia completato le sezioni principali sulle percezioni, interrompendosi solamente nelle parti economiche o sociodemografiche.

In [61]:
# Seleziono i questionari con almeno una risposta,
# ma con meno di 40 domande principali compilate
id_residenti_parziali = completamento_residenti.loc[
    completamento_residenti["Risposte compilate"].between(1, 39),
    "ID risposta"
].tolist()

# Seleziono i questionari parziali ancora presenti
questionari_parziali_residenti = df_residenti_pulito[
    df_residenti_pulito["ID risposta"].isin(id_residenti_parziali)
]

# Creo un riepilogo sintetico
riepilogo_parziali_residenti = []

for _, riga in questionari_parziali_residenti.iterrows():

    colonne_compilate = [
        colonna
        for colonna in colonne_analisi_residenti
        if pd.notna(riga[colonna])
    ]

    colonne_mancanti = [
        colonna
        for colonna in colonne_analisi_residenti
        if pd.isna(riga[colonna])
    ]

    riepilogo_parziali_residenti.append({
        "ID risposta": riga["ID risposta"],
        "Risposte compilate": len(colonne_compilate),
        "Ultima domanda compilata": (
            colonne_compilate[-1]
            if colonne_compilate
            else None
        ),
        "Prima domanda mancante": (
            colonne_mancanti[0]
            if colonne_mancanti
            else None
        )
    })

# Trasformo il riepilogo in una tabella
riepilogo_parziali_residenti = pd.DataFrame(
    riepilogo_parziali_residenti
).sort_values(
    "Risposte compilate"
).reset_index(drop=True)

pd.set_option("display.max_colwidth", None)

print(
    "Questionari parziali individuati:",
    len(riepilogo_parziali_residenti)
)

riepilogo_parziali_residenti

Questionari parziali individuati: 13

,ID risposta,Risposte compilate,Ultima domanda compilata,Prima domanda mancante
0,35,27,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,Quanto sei d’accordo con le seguenti affermazioni? [Mi sento ascoltato/a quando esprimo idee o proposte sul futuro del territorio]
1,83,28,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,"Quanto sei d’accordo con le seguenti affermazioni? [Quando vedo un problema o un’opportunità nel paese, penso di poter fare qualcosa]"
2,99,28,Quanto sei d’accordo con le seguenti affermazioni? [Mi sento mentalmente ed emotivamente a mio agio qui],Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?
3,30,29,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?"
4,76,29,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?"
5,51,29,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?"
6,211,29,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?"
7,17,29,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?"
8,138,34,Cambiamento del valore patrimoniale,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?"
9,24,35,Cambiamento del valore patrimoniale,Genere
10,53,35,Cambiamento del valore patrimoniale,Genere
11,88,35,Cambiamento del valore patrimoniale,Genere
12,127,38,Cambiamento del valore patrimoniale,Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?

### Esito del controllo delle compilazioni parziali

I 13 questionari parziali non vengono esclusi dall’analisi.

La maggior parte dei partecipanti ha completato le sezioni principali relative alla percezione del territorio, saltando solamente alcune domande oppure interrompendo la compilazione nelle sezioni economiche o sociodemografiche finali.

Le analisi successive verranno quindi effettuate utilizzando, per ogni domanda, il relativo numero di risposte valide. In questo modo vengono conservate tutte le informazioni disponibili senza attribuire valori alle risposte mancanti.

## Profilo sociodemografico dei residenti

In questa sezione viene descritta la composizione del campione dei residenti e frequentatori abituali attraverso le seguenti variabili:

* genere;
* fascia d’età;
* titolo di studio;
* professione;
* numero di anni di residenza o frequentazione abituale.

Le percentuali vengono calcolate sul totale delle risposte valide disponibili per ciascuna domanda.

In [62]:
# Variabili sociodemografiche e di permanenza da analizzare
variabili_profilo_residenti = [
    "Genere",
    "Età:",
    "Titolo di studio",
    "Professione",
    "Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?"
]

# Creo e mostro una tabella per ogni variabile
for variabile in variabili_profilo_residenti:
    print("\n" + "=" * 80)
    print(variabile.upper())
    print("=" * 80)

    display(
        tabella_percentuali(
            df_residenti_pulito,
            variabile
        )
    )

================================================================================
GENERE
================================================================================

        Genere  Numero di risposte  Percentuale
0      Femmina                  40         56.3
1      Maschio                  28         39.4
2  Non binario                   3          4.2

================================================================================
ETÀ:
================================================================================

    Età:  Numero di risposte  Percentuale
0  18–30                  19         27.1
1  46–65                  18         25.7
2  31–45                  17         24.3
3    >65                  16         22.9

================================================================================
TITOLO DI STUDIO
================================================================================

,Titolo di studio,Numero di risposte,Percentuale
0,Licenza Superiore,27,38.0
1,Laurea Magistrale / Laurea Vecchio Ordinamento,19,26.8
2,Licenza Media,15,21.1
3,Laurea Triennale,6,8.5
4,Specializzazione Post-Laurea,4,5.6

================================================================================
PROFESSIONE
================================================================================

                    Professione  Numero di risposte  Percentuale
0                  Pensionato/a                  17         23.9
1  Lavoro a tempo indeterminato                  14         19.7
2  Imprenditore / imprenditrice                  12         16.9
3          Studente/studentessa                  10         14.1
4       Libero/a professionista                   8         11.3
5    Lavoro a tempo determinato                   5          7.0
6                 Disoccupato/a                   3          4.2
7                         Altro                   2          2.8

================================================================================
DA QUANTI ANNI VIVI A/FREQUENTI ABITUALMENTE MONTALTO DELLE MARCHE?
================================================================================

,Da quanti anni vivi a/frequenti abitualmente Montalto delle Marche?,Numero di risposte,Percentuale
0,da sempre,67,81.7
1,>10,9,11.0
2,1–5,4,4.9
3,6–10,2,2.4

## Percezione del territorio e della comunità

In questa sezione vengono analizzate le affermazioni relative alla partecipazione, alla fiducia, al senso di comunità, al legame con il territorio, alla cultura, alla sostenibilità e al benessere percepito.

Le risposte sono espresse su una scala da 1 a 7.

Per ciascuna affermazione vengono calcolati:

* il numero di risposte valide;
* il punteggio medio;
* la mediana;
* la percentuale di valutazioni positive, corrispondenti ai punteggi compresi tra 5 e 7.

In [63]:
# Individuo le colonne con le affermazioni su scala da 1 a 7
colonne_valutazioni_residenti = [
    colonna
    for colonna in df_residenti_pulito.columns
    if colonna.startswith(
        "Quanto sei d’accordo con le seguenti affermazioni?"
    )
]

# Creo il riepilogo delle valutazioni
riepilogo_valutazioni_residenti = []

for colonna in colonne_valutazioni_residenti:
    risposte = pd.to_numeric(
        df_residenti_pulito[colonna],
        errors="coerce"
    ).dropna()

    # Estraggo il testo dell'affermazione
    affermazione = colonna.split("[", 1)[-1].rstrip("]")

    riepilogo_valutazioni_residenti.append({
        "Affermazione": affermazione,
        "Risposte valide": len(risposte),
        "Media": risposte.mean(),
        "Mediana": risposte.median(),
        "Valutazioni positive (%)": (
            risposte.ge(5).mean() * 100
        )
    })

# Trasformo i risultati in una tabella
riepilogo_valutazioni_residenti = pd.DataFrame(
    riepilogo_valutazioni_residenti
)

# Arrotondo i valori
riepilogo_valutazioni_residenti["Media"] = (
    riepilogo_valutazioni_residenti["Media"].round(2)
)

riepilogo_valutazioni_residenti["Mediana"] = (
    riepilogo_valutazioni_residenti["Mediana"].round(1)
)

riepilogo_valutazioni_residenti[
    "Valutazioni positive (%)"
] = (
    riepilogo_valutazioni_residenti[
        "Valutazioni positive (%)"
    ].round(1)
)

# Ordino dalla media più alta alla più bassa
riepilogo_valutazioni_residenti = (
    riepilogo_valutazioni_residenti
    .sort_values("Media", ascending=False)
    .reset_index(drop=True)
)

riepilogo_valutazioni_residenti

,Affermazione,Risposte valide,Media,Mediana,Valutazioni positive (%)
0,"Cerco di adottare comportamenti rispettosi dell’ambiente negli spazi pubblici e culturali (rifiuti, energia, mobilità, uso delle risorse)",83,6.42,7.0,95.2
1,Nella mia vita quotidiana presto attenzione a ridurre l’impatto ambientale delle mie azioni nel territorio in cui vivo,83,6.16,7.0,91.6
2,Presto attenzione alla cura degli spazi pubblici,83,6.14,7.0,90.4
3,Penso alle conseguenze future delle scelte fatte oggi sul territorio,83,5.93,7.0,88.0
4,Mi sento emotivamente legato/a a questo luogo,83,5.66,6.0,80.7
5,Questo territorio rappresenta una parte importante di chi sono,83,5.60,6.0,81.9
6,Mi dispiacerebbe molto dover lasciare questo luogo,83,5.45,6.0,73.5
7,Sono orgoglioso/a di vivere qui,83,5.36,6.0,75.9
8,La cultura ha un ruolo importante nella mia vita quotidiana,83,5.16,6.0,68.7
9,Le attività culturali mi fanno riflettere sul presente e sul futuro del territorio,83,5.05,6.0,66.3
10,Le relazioni sociali contribuiscono positivamente alla mia qualità della vita,83,5.04,5.0,72.3
11,Mi sento mentalmente ed emotivamente a mio agio qui,83,5.01,5.0,67.5
12,Sento di poter contribuire attivamente alla vita del mio territorio,83,4.98,5.0,63.9
13,Vivo questo luogo come un ambiente che favorisce il benessere,83,4.88,5.0,67.5
14,Mi sento soddisfatto/a della mia vita nel territorio,83,4.76,5.0,65.1
15,Gli spazi culturali mi stimolano a imparare cose nuove,83,4.73,5.0,56.6
16,Ho fiducia nella mia capacità di avviare o partecipare a iniziative locali,83,4.59,5.0,60.2
17,"Partecipo ad attività culturali locali (eventi, laboratori, incontri)",83,4.47,5.0,56.6
18,"Quando vedo un problema o un’opportunità nel paese, penso di poter fare qualcosa",82,4.46,5.0,54.9
19,Vedo prospettive positive per il futuro della comunità,83,4.33,4.0,47.0
20,"Mi sento coinvolto/a, non solo spettatore/trice",83,4.16,4.0,47.0
21,Mi sento parte di una comunità,83,4.00,4.0,42.2
22,Mi sento ascoltato/a quando esprimo idee o proposte sul futuro del territorio,82,3.45,3.5,28.0
23,"C’è fiducia reciproca tra abitanti, associazioni e operatori locali",83,3.41,3.0,27.7
24,Nel mio territorio le persone collaborano tra loro,82,3.05,3.0,20.7

### Sintesi delle percezioni per area tematica

Le 25 affermazioni vengono raggruppate in sei dimensioni:

* capacità di iniziativa e partecipazione;
* coesione sociale e senso di comunità;
* legame identitario con il territorio;
* partecipazione e coinvolgimento culturale;
* responsabilità ambientale;
* benessere e prospettive future.

Per ciascun partecipante viene calcolato il punteggio medio nelle diverse aree. Il punteggio viene considerato valido quando è stata compilata almeno la metà delle affermazioni appartenenti all’area.

Successivamente vengono calcolati il punteggio medio complessivo e la percentuale di valutazioni positive, corrispondenti a un punteggio medio pari o superiore a 5.

In [64]:
import math

# Associo il testo breve dell'affermazione
# al nome completo della relativa colonna
mappa_colonne_residenti = {
    colonna.split("[", 1)[-1].rstrip("]"): colonna
    for colonna in colonne_valutazioni_residenti
}

# Raggruppo le affermazioni nelle aree tematiche
aree_residenti = {
    "Iniziativa e partecipazione": [
        "Sento di poter contribuire attivamente alla vita del mio territorio",
        "Quando vedo un problema o un’opportunità nel paese, penso di poter fare qualcosa",
        "Mi sento ascoltato/a quando esprimo idee o proposte sul futuro del territorio",
        "Ho fiducia nella mia capacità di avviare o partecipare a iniziative locali"
    ],

    "Coesione sociale e comunità": [
        "Nel mio territorio le persone collaborano tra loro",
        "Mi sento parte di una comunità",
        "C’è fiducia reciproca tra abitanti, associazioni e operatori locali"
    ],

    "Legame con il territorio": [
        "Mi sento emotivamente legato/a a questo luogo",
        "Sono orgoglioso/a di vivere qui",
        "Questo territorio rappresenta una parte importante di chi sono",
        "Mi dispiacerebbe molto dover lasciare questo luogo"
    ],

    "Cultura e coinvolgimento": [
        "Partecipo ad attività culturali locali (eventi, laboratori, incontri)",
        "Gli spazi culturali mi stimolano a imparare cose nuove",
        "Le attività culturali mi fanno riflettere sul presente e sul futuro del territorio",
        "Mi sento coinvolto/a, non solo spettatore/trice",
        "La cultura ha un ruolo importante nella mia vita quotidiana"
    ],

    "Responsabilità ambientale": [
        "Presto attenzione alla cura degli spazi pubblici",
        "Penso alle conseguenze future delle scelte fatte oggi sul territorio",
        "Nella mia vita quotidiana presto attenzione a ridurre l’impatto ambientale delle mie azioni nel territorio in cui vivo",
        "Cerco di adottare comportamenti rispettosi dell’ambiente negli spazi pubblici e culturali (rifiuti, energia, mobilità, uso delle risorse)"
    ],

    "Benessere e prospettive future": [
        "Mi sento soddisfatto/a della mia vita nel territorio",
        "Vivo questo luogo come un ambiente che favorisce il benessere",
        "Le relazioni sociali contribuiscono positivamente alla mia qualità della vita",
        "Vedo prospettive positive per il futuro della comunità",
        "Mi sento mentalmente ed emotivamente a mio agio qui"
    ]
}

# Creo un DataFrame che conterrà il punteggio
# ottenuto da ogni partecipante nelle diverse aree
punteggi_aree_residenti = pd.DataFrame(
    index=df_residenti_pulito.index
)

for area, affermazioni in aree_residenti.items():

    # Recupero i nomi completi delle colonne
    colonne_area = [
        mappa_colonne_residenti[affermazione]
        for affermazione in affermazioni
    ]

    # Converto le risposte in valori numerici
    valori_area = df_residenti_pulito[
        colonne_area
    ].apply(
        pd.to_numeric,
        errors="coerce"
    )

    # Richiedo almeno metà delle affermazioni compilate
    minimo_risposte = math.ceil(len(colonne_area) / 2)

    # Calcolo la media individuale dell'area
    punteggio_area = valori_area.mean(axis=1)

    # Imposto come mancante il punteggio di chi
    # non ha risposto ad almeno metà delle affermazioni
    punteggio_area[
        valori_area.notna().sum(axis=1) < minimo_risposte
    ] = pd.NA

    punteggi_aree_residenti[area] = punteggio_area


# Creo il riepilogo generale delle aree
riepilogo_aree_residenti = []

for area in punteggi_aree_residenti.columns:
    punteggi_validi = pd.to_numeric(
        punteggi_aree_residenti[area],
        errors="coerce"
    ).dropna()

    riepilogo_aree_residenti.append({
        "Area tematica": area,
        "Numero di affermazioni": len(aree_residenti[area]),
        "Risposte valide": len(punteggi_validi),
        "Punteggio medio": punteggi_validi.mean(),
        "Mediana": punteggi_validi.median(),
        "Valutazioni positive (%)": (
            punteggi_validi.ge(5).mean() * 100
        )
    })

riepilogo_aree_residenti = pd.DataFrame(
    riepilogo_aree_residenti
)

# Arrotondo i risultati
riepilogo_aree_residenti["Punteggio medio"] = (
    riepilogo_aree_residenti["Punteggio medio"].round(2)
)

riepilogo_aree_residenti["Mediana"] = (
    riepilogo_aree_residenti["Mediana"].round(2)
)

riepilogo_aree_residenti["Valutazioni positive (%)"] = (
    riepilogo_aree_residenti[
        "Valutazioni positive (%)"
    ].round(1)
)

# Ordino dalla valutazione più alta alla più bassa
riepilogo_aree_residenti = (
    riepilogo_aree_residenti
    .sort_values(
        "Punteggio medio",
        ascending=False
    )
    .reset_index(drop=True)
)

riepilogo_aree_residenti

,Area tematica,Numero di affermazioni,Risposte valide,Punteggio medio,Mediana,Valutazioni positive (%)
0,Responsabilità ambientale,4,83,6.16,6.50,89.2
1,Legame con il territorio,4,83,5.52,6.00,75.9
2,Benessere e prospettive future,5,83,4.80,5.00,54.2
3,Cultura e coinvolgimento,5,83,4.71,5.20,50.6
4,Iniziativa e partecipazione,4,83,4.37,4.25,39.8
5,Coesione sociale e comunità,3,83,3.49,3.67,27.7

## Effetti percepiti del progetto Metroborgo

In questa sezione vengono analizzate le opinioni dei residenti sugli effetti del progetto Metroborgo.

L’analisi considera:

* il miglioramento percepito della vita sociale;
* il dialogo con persone con background culturali differenti;
* la possibilità di favorire nuove imprese culturali, creative e turistiche;
* il cambiamento percepito del reddito;
* la qualità dell’ambiente;
* l’influenza sulla qualità della vita;
* la soddisfazione rispetto agli investimenti;
* il miglioramento della visibilità di Montalto delle Marche.

Le percentuali vengono calcolate sul totale delle risposte valide disponibili per ciascuna domanda.

In [66]:
# Parole chiave sufficienti a identificare le domande
parole_chiave_effetti = [
    "miglioramento della tua vita sociale",
    "background culturale differente",
    "favorire nuove imprese",
    "come è cambiato il tuo reddito",
    "cambiamento della qualità dell’ambiente",
    "influenzato la qualità della tua vita",
    "soddisfatto/a degli investimenti",
    "visibilità nazionale e internazionale"
]

# Individuo i nomi esatti delle colonne presenti nel DataFrame
variabili_effetti_metroborgo = []

for parola_chiave in parole_chiave_effetti:
    corrispondenze = [
        colonna
        for colonna in df_residenti_pulito.columns
        if parola_chiave.lower() in colonna.lower()
    ]

    if len(corrispondenze) == 1:
        variabili_effetti_metroborgo.append(corrispondenze[0])
    else:
        print(
            f"Attenzione: trovate {len(corrispondenze)} colonne "
            f"per la parola chiave '{parola_chiave}'"
        )

# Creo una tabella di frequenze e percentuali per ogni domanda
for variabile in variabili_effetti_metroborgo:
    print("\n" + "=" * 90)
    print(variabile.upper())
    print("=" * 90)

    display(
        tabella_percentuali(
            df_residenti_pulito,
            variabile
        )
    )

==========================================================================================
GRAZIE ALLE ATTIVITÀ DEL PROGETTO METROBORGO, HAI PERCEPITO UN MIGLIORAMENTO DELLA TUA VITA SOCIALE?
==========================================================================================

,"Grazie alle attività del progetto Metroborgo, hai percepito un miglioramento della tua vita sociale?",Numero di risposte,Percentuale
0,Abbastanza,28,33.7
1,Per niente,23,27.7
2,Poco,18,21.7
3,Molto,14,16.9

==========================================================================================
GRAZIE AL PROGETTO METROBORGO HAI DIALOGATO CON CHI HA UN BACKGROUND CULTURALE DIFFERENTE DAL TUO?
==========================================================================================

,Grazie al progetto Metroborgo hai dialogato con chi ha un background culturale differente dal tuo?,Numero di risposte,Percentuale
0,Abbastanza,24,28.9
1,Per niente,24,28.9
2,Poco,23,27.7
3,Molto,12,14.5

==========================================================================================
CREDI CHE IL PROGETTO METROBORGO POSSA FAVORIRE NUOVE IMPRESE NEL SETTORE CULTURALE E CREATIVO E NEL TURISMO?
==========================================================================================

,Credi che il progetto Metroborgo possa favorire nuove imprese nel settore culturale e creativo e nel turismo?,Numero di risposte,Percentuale
0,Sì,65,79.3
1,No,17,20.7

==========================================================================================
A SEGUITO DEGLI INVESTIMENTI REALIZZATI CON IL PROGETTO METROBORGO, COME È CAMBIATO IL TUO REDDITO PERSONALE O FAMILIARE?
==========================================================================================

,"A seguito degli investimenti realizzati con il progetto Metroborgo, come è cambiato il tuo reddito personale o familiare?",Numero di risposte,Percentuale
0,È rimasto invariata,57,77.0
1,È aumentato leggermente,10,13.5
2,È diminuito molto,3,4.1
3,È diminuito leggermente,3,4.1
4,È aumentato molto,1,1.4

==========================================================================================
COME VALUTI IL CAMBIAMENTO DELLA QUALITÀ DELL’AMBIENTE (PAESAGGIO URBANO, SPAZI PUBBLICI, SERVIZI PUBBLICI) DOPO GLI INVESTIMENTI REALIZZATI CON IL PROGETTO METROBORGO?
==========================================================================================

,"Come valuti il cambiamento della qualità dell’ambiente (paesaggio urbano, spazi pubblici, servizi pubblici) dopo gli investimenti realizzati con il progetto Metroborgo?",Numero di risposte,Percentuale
0,Migliorata,36,48.0
1,Invariata,22,29.3
2,Molto migliorata,13,17.3
3,Molto peggiorata,3,4.0
4,Peggiorata,1,1.3

==========================================================================================
NEL COMPLESSO, IN CHE MISURA GLI INVESTIMENTI REALIZZATI DAL PROGETTO METROBORGO HANNO INFLUENZATO LA QUALITÀ DELLA TUA VITA?
==========================================================================================

,"Nel complesso, in che misura gli investimenti realizzati dal progetto Metroborgo hanno influenzato la qualità della tua vita?",Numero di risposte,Percentuale
0,Influenza positiva,33,44.0
1,Nessuna influenza,33,44.0
2,Influenza negativa,5,6.7
3,Influenza molto positiva,3,4.0
4,Influenza molto negativa,1,1.3

==========================================================================================
NEL COMPLESSO, QUANTO SEI SODDISFATTO/A DEGLI INVESTIMENTI REALIZZATI DAL PROGETTO METROBORGO NEL TUO TERRITORIO?
==========================================================================================

,"Nel complesso, quanto sei soddisfatto/a degli investimenti realizzati dal progetto Metroborgo nel tuo territorio?",Numero di risposte,Percentuale
0,Abbastanza soddisfatto/a,29,38.7
1,Molto soddisfatto/a,19,25.3
2,Poco soddisfatto/a,13,17.3
3,Completamente soddisfatto/a,8,10.7
4,Per niente soddisfatto/a,6,8.0

==========================================================================================
CREDI CHE IL PROGETTO METROBORGO ABBIA CONTRIBUITO A MIGLIORARE LA VISIBILITÀ NAZIONALE E INTERNAZIONALE DI MONTALTO DELLE MARCHE?
==========================================================================================

,Credi che il progetto Metroborgo abbia contribuito a migliorare la visibilità nazionale e internazionale di Montalto delle Marche?,Numero di risposte,Percentuale
0,Sì,51,71.8
1,No,20,28.2

## Patrimonio e investimenti economici

In questa sezione vengono analizzati:

* il cambiamento percepito del valore patrimoniale;
* la realizzazione di investimenti economici nel comune;
* l’ammontare degli investimenti effettuati.

Le percentuali vengono calcolate sul totale delle risposte valide disponibili per ciascuna domanda.

In [68]:
# Variabili relative al patrimonio e agli investimenti
variabili_patrimonio_investimenti = [
    "Cambiamento del valore patrimoniale",
    "A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?",
    "Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?"
]

# Creo una tabella di frequenze e percentuali
# per ciascuna variabile
for variabile in variabili_patrimonio_investimenti:
    print("\n" + "=" * 90)
    print(variabile.upper())
    print("=" * 90)

    display(
        tabella_percentuali(
            df_residenti_pulito,
            variabile
        )
    )

==========================================================================================
CAMBIAMENTO DEL VALORE PATRIMONIALE
==========================================================================================

,Cambiamento del valore patrimoniale,Numero di risposte,Percentuale
0,È rimasto invariato,49,65.3
1,È aumentato leggermente,17,22.7
2,È aumentato molto,4,5.3
3,Risposta multipla: È rimasto invariato / È aumentato leggermente,2,2.7
4,È diminuito molto,2,2.7
5,È diminuito leggermente,1,1.3

==========================================================================================
A SEGUITO DEL PROGETTO METROBORGO, HAI EFFETTUATO INVESTIMENTI ECONOMICI NEL COMUNE DI MONTALTO DELLE MARCHE?
==========================================================================================

,"A seguito del progetto Metroborgo, hai effettuato investimenti economici nel comune di Montalto delle Marche?",Numero di risposte,Percentuale
0,No,66,88.0
1,Sì,9,12.0

==========================================================================================
QUAL È STATO APPROSSIMATIVAMENTE L’AMMONTARE COMPLESSIVO DEGLI INVESTIMENTI EFFETTUATI?
==========================================================================================

,Qual è stato approssimativamente l’ammontare complessivo degli investimenti effettuati?,Numero di risposte,Percentuale
0,Oltre 100.000 €,4,44.4
1,Meno di 5.000 €,4,44.4
2,Tra 5.000 € e 20.000 €,1,11.1